### ISSUE TITLE
Browser crashing on VFB2

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#101]
Various loading issues

**Comment by temjones** [comment]
![image](https://user-images.githubusercontent.com/22234198/32554116-b80fdf56-c490-11e7-8d69-f150bd15f1f2.png)

**Comment by Robbie1977** [comment]
Server found to be causing dropped packets taken out of service. Should be resolved but better monitor the situation for a month.

Please flag on this ticket if any of these issues reoccur?
