### ISSUE TITLE
Establish strategy to minimize use of internal terminology for templates and painted domains

### ISSUE THREAD

**Issue by temjones** [VirtualFlyBrain/geppetto-vfb#102]
Eg: painted domains and templates - Names are very unintuitive

**Comment by dosumis** [comment]
I've narrowed the scope of this ticket.  We might want a label for issues of this type.  Perhaps jargon-busting ?

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#69

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#83
