### ISSUE TITLE
trackpad 2 finger scrolling fails in firefox on slice viewer

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#104]
Can move through the stack using trackpad gestures in firefox.

**Comment by Robbie1977** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=927702 for a potential fix:

```Disabling the two-finger "swipe between pages" gesture in system preferences seems to be an adequate workaround for the time being.```

**Comment by Robbie1977** [comment]
Workarounds don't seem to work anymore.

**Comment by ah963** [comment]
the scroll wheel isnt working on the slice viewer to move through the stack in firefox (54.0 64bit) , although it is in other browsers

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#72

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#84
