### ISSUE TITLE
As a user, I want to be made aware if choosing to display an image will mean switching to a new template.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#105]
The current behavior - trying to open a new tab with no warning when choosing an image registered to a different template to the one currently displayed, is too jarring.   Users may not initially be aware that different images available on VFB are registered to different templates, so a warning message that makes this clear would be good.  A better way to display template metadata (in its own widget?) - separate from TermInfo/Control panel would also be good.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#73

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#85
