### ISSUE TITLE
Give templates longer, more informative names

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#107]

**Comment by dosumis** [comment]
Current names. JFRC2 & Ito half brain are obscure.  Template name should make clear what region it is for, and that it is a template.

Suggest:  

adult brain template JFRC2
Ito half brain -> adult brain template Ito2014 (or adult half brain template Ito2014)

Each should have some descriptive text in addition to licensing and Acknowledgment information.

This can be derived from information here:

http://www.virtualflybrain.org/site/vfb_site/template_files_downloads.htm

**Comment by dosumis** [comment]
Changed labels to

adult brain template JFRC2
adult brain template Ito2014

- [ ] TODO: - add description etc.

**Comment by dosumis** [comment]
```js
{
  "iri": "http://virtualflybrain.org/reports/VFB_00017894",
  "short_form": "VFB_00017894",
  "definition": "An adult brain template created by Arnim Jenett (Janelia Research Campus) and painted according the the BrainName standard by Arnim Jenett, Kazunori Shinomiya and Kei Ito (Tokyo University) from a staining with the neuropil marker nc82. The image was captured at 20x magnification. The voxel size is 0.62x0.62x0.62 micron.",
  "label": "adult brain template JFRC2",
  "is_obsolete": false
}
```

```js

{
  "iri": "http://virtualflybrain.org/reports/VFB_00030786",
  "short_form": "VFB_00030786",
  "definition": "The official template for the BrainName nomnclature and accompanying painted domains for the Brain Name nomenclature (Ito et al., 2014).  This ticolor brain feautres a presynaptic marker (n-syb-GFP, green), a post synaptic marker (GABA receptor targeted Rdl-HA receptor, blue) and a cytoplasmic marker (Cytoplasmic DsRed, red).",
  "label": "adult brain template Ito2014",
  "is_obsolete": false
}

```

**Comment by Robbie1977** [comment]
Issue moved to [VirtualFlyBrain/VFB2 #58](https://github.com/VirtualFlyBrain/VFB2/issues/58) via [**ZenHub**](https://www.zenhub.com/)
