### ISSUE TITLE
As a user, I want clear feedback about which template I'm currently on, distinct from information about domains on that template

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#108]
This will become more critical as templates proliferate.

Suggested change: Move template info from control panel to a separate widget.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#75

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#87
