### ISSUE TITLE
Add publication pages (inside TermInfo)

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#110]
@dosumis commented on [Tue Jun 16 2015](https://github.com/VirtualFlyBrain/VFB_2/issues/5)

This page to be used for links from pubmed/PMC using their linkout mechanisms.  
### Content:
- Pub metadata:  Keep this minimal and rely on linking(?)
  - But how minimal? Is miniref really enough, and if not where do we pull data from?
- Links to anatomical structures
  - Based on refs in ontology?
  - From annotations
    - Also display details of annotation?

---

@jefferis commented on [Tue Jun 16 2015](https://github.com/VirtualFlyBrain/VFB_2/issues/5#issuecomment-112374112)

Hi @dosumis Could you clarify what page you are referring to here?

---

@dosumis commented on [Tue Jun 16 2015](https://github.com/VirtualFlyBrain/VFB_2/issues/5#issuecomment-112377333)

We don't have pages for pubs yet, but it is not unreasonable to have them - presenting data associated with a particular pub.  Useful in its own right, but the immediate demand for these comes from wanting a page to link to from pubs on pubmed and PMC (see linked ticket).  It could also provide a good way for authors/community to see how we've annotated.  Coupled with comment threads, they could give feedback if they disagree.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#76

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#88
