### ISSUE TITLE
Reproductive terms and dev stages in female organism parts query

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#111]
@mmc46 commented on [Mon Nov 06 2017](https://github.com/VirtualFlyBrain/VFB_owl/issues/37)

I haven't checked the ontology carefully, so flagging this here to be checked.

A query for parts of 'female organism' shows some results that a user might not expect in a neural focused site.
- terms under 'female germline cell' (FBbt:00057012), oocyte (FBbt:00004886), including oocyte developmental stages.

It might be better if these terms were removed or hidden. That would make it easier to find images or classes that are female specific.

---

@dosumis commented on [Sat Nov 11 2017](https://github.com/VirtualFlyBrain/VFB_owl/issues/37#issuecomment-343674730)

There are a  couple of more general issues here:
   - we used to attempt to filter results on to be nervous system specific, but no longer do so.  Should we discuss adding this back?
   - We need to think about how to add simple, intuitive query restrictions for neurons in males vs females.

Each would need a more general ticket for discussion/prioritization.

**Comment by mmc46** [comment]
Ok, I though the nervous system filtering was still on.

**Comment by dosumis** [comment]
Replaced by #116 and virtualflybrain/Management#64
