### ISSUE TITLE
Python backend migration analysis

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1139]
note - flag once reached the 4h how deep this rabbit hole is.

**Comment by jrmartin** [comment]
Update on analysis:

pygeppetto has most of the Java version of Geppetto working already https://github.com/openworm/pygeppetto 

These is what's missing:

We will need to migrate these bundles from Java to python:
- org.geppetto.model.swc
- uk.ac.vfb.geppetto

We would also need to migrate the query processors we are using, not sure yet how long this will take:
https://github.com/openworm/org.geppetto.datasources/tree/master/src/main/java/org/geppetto/datasources

There's already an implementation of the neo4j query processor https://github.com/openworm/pygeppetto/blob/development/pygeppetto/services/data_source/neo4j.py
