### ISSUE TITLE
Clipping of text in queries in firefox

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#117]
@Robbie1977 commented on [Tue Nov 21 2017](https://github.com/VirtualFlyBrain/pipeline/issues/9)

![image](https://user-images.githubusercontent.com/4630768/33079454-86935cc2-cecd-11e7-946a-68e0ad521f14.png)

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#78

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#79

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#90
