### ISSUE TITLE
NBLAST uploader design

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1171]
key points for the design:

functionalities:
- the user will have to upload an swc file
- the user will have to select a template to be used from a dropdown configurable list (robbie will provide this list).
- the swc will be displayed in the 3d viewer
- once the upload is successfull the user can trigger an nblast pushing a button

To be discussed:
- will the url be generated by the frontend (the nblast query will have at least to return to us the new instance id) or will this be computed by the external server and then sent via email with notification once the analysis is completed?

Frontend requirements:
- upload dropzone
- dropdown list
- button to trigger the nblast
- a bit of space where to display some text (this can be filled dynamically as response of the trigger, do not anything too fancy since the design is still in progress, just a pure text space area/div is sufficient).
- checkbox to get consent from the user to store the url in this browser/client

The url will have to be retained per session and intra-session, so per client (cookie or web storage to be used here).

Note: there might be an additional dropdown to let the user select also the dataset to be used.

**Comment by jrmartin** [comment]
Hello @Robbie1977, 

One of the requirements for this is : "the user will have to select a template to be used from a dropdown configurable list (robbie will provide this list).".

What's the list of templates?

**Comment by jrmartin** [comment]
@ddelpiano Design of component, it will be a dialog that opens from the Tools menu.

![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/a102701c-3d73-44e6-be18-85b6cdbe97eb)

![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/2a97e2dd-9130-4dc3-9450-8438fdbf725e)
