### ISSUE TITLE
Downloader instances list

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1173]
Changes requested:
- we'll have a global type list with checkboxes (as it is now, so nothing much to do here).
- Add list of instances with checkboxes to select a single instance
- add checkbox all instances to select/deselect all.

- In term of functionality the lists are static in the sense that the user can select all the types and all the instances but the model does not guarantee that a certain instance has all the type.
- The instances list will have to show all the instances presents in the scene, same list we have for the list viewer/control panel component.

the layout will be similar to 

- [ ] type 1
- [ ] type 2
- [ ] type 3
- [ ] type 4
- [ ] type 5
----------------
- [ ] all instances
  - [ ] Instance 1
  - [ ] Instance 2
  - [ ] Instance 3
  - [ ] Instance 4

**Comment by jrmartin** [comment]
@ddelpiano Implemented this one, needs CSS styling :

![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/72b1a060-db8b-4ed3-a349-94b8bd5e23ed)
