### ISSUE TITLE
Too many example images of 'adult brain' 

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/geppetto-vfb#119]
The 'adult brain' example images seem to be a massive random collection of GMR Gal4 images
![screen shot 2017-12-07 at 09 45 45](https://user-images.githubusercontent.com/26765505/33708931-b8b8af50-db33-11e7-95be-795470980613.png)

and if you click on 'list all example images' you get 3000+ if it doesn't freeze trying to load them all

![screen shot 2017-12-07 at 09 48 15](https://user-images.githubusercontent.com/26765505/33708975-daf10eb4-db33-11e7-8674-ac43a95bd2dc.png)

Is this an intended feature?

**Comment by dosumis** [comment]
Fixed. Moving to review.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#91
