### ISSUE TITLE
Extend tests to cover new download and uploader components

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1192]
Downloader:
- not controversial, we can add one instance to the scene that has obj and swc, select all instances and check that the archive has the required data.

Uploader:
- To follow up, a good strategy it can be to just test the frontend side of things, so open the modal, select a template, upload an swc and check that the component reacts correctly. Generating the nblast results might result in queueing not needed instances for the file server and also it would be difficult to hold the tests for 30+ mins waiting for the results, plus the strategy for opening the query builder from the url is already covered by other tests so no need to extend tests for that.

**Comment by jrmartin** [comment]
The tests for these are now part of this open PR, with the rest of the uploader too. 

Unfortunately because of browser restrictions we can't test the case of uploading a file from the local system, so that wasn't added it.
