### ISSUE TITLE
Term Info window is blank when reopened

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/geppetto-vfb#121]
When you close then reopen the term info window it is blank. Clicking the arrows restores previously viewed info.

Recorded example here
https://www.useloom.com/share/4f15247dc9f240079bc4d9bbca467ccd

When term info window is closed, searching for a feature does not reopen it. When it is reopened, the feature is missing.

Recorded example here
https://www.useloom.com/share/e37f1aa45c884dacbf824049fa081e88

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#107
