### ISSUE TITLE
Model for MB - painted domain JFRC2 (VFB_00030867) is wrong

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/geppetto-vfb#122]
3D model isn't the mushroom body.
<img width="913" alt="screen shot 2017-12-12 at 12 22 49" src="https://user-images.githubusercontent.com/26765505/33884364-443cf7c8-df37-11e7-96a1-d205d91ccd05.png">

I think it's (half) the calyx of the adult mushroom body.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#92
