### ISSUE TITLE
Pass search filters into solr query to ensure displayable results are at the top of list.

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1239]

**Comment by jrmartin** [comment]
@ddelpiano @Robbie1977  Do we add the (+) and (-) as options to the filter set? Or how do we let the user choose between the (+) or (-)? 

We can add them to the list of filters, and depending which one of them is selected, we assigned the value of "bq=" to it?
![image](https://user-images.githubusercontent.com/4562825/139745747-e37e43d1-d8e5-4176-adc0-d03b599f7ace.png)

**Comment by Robbie1977** [comment]
@jrmartin I think the requirement has got a bit confusing.

NO changes to the filters tools/menu 

all we need to do is take the selected filters and add them to the solr query parameters 

so if we have:
![image](https://user-images.githubusercontent.com/4630768/140032539-3ad88b2f-7090-4ead-80a2-6daa975c19e1.png)

Then we need to add these additional parameters to the solr query:
bq += " facets_annotation:DataSet^100 facets_annotation:Deprecated^0.001" 

So ^100 moves the results score up and 0.001 down 

The original parameters are: 
```
var datasourceConfiguration = {
  "url": "https://solr.virtualflybrain.org/solr/ontology/select",
  "query_settings":
    {
      "q": "$SEARCH_TERM$ OR $SEARCH_TERM$* OR *$SEARCH_TERM$*",
      "defType": "edismax",
      "qf": "label^100 synonym^100 label_autosuggest_ws label_autosuggest_e label_autosuggest synonym_autosuggest_ws synonym_autosuggest shortform_autosuggest",
      "indent": "true",
      "fl": "short_form,label,synonym,id,facets_annotation",
      "start": "0",
      "pf":"true",
      "fq": [
        "shortform_autosuggest:VFB* OR shortform_autosuggest:FB* OR facets_annotation:DataSet OR facets_annotation:pub"
      ],
      "rows": "100",
      "wt": "json",
      "bq": "shortform_autosuggest:VFB*^110.0 shortform_autosuggest:FBbt*^100.0 label_s:\"\"^2 synonym_s:\"\" short_form:FBbt_00003982^2 facets_annotation:Deprecated^0.001"
    }
};
```

so after the change "bq" will be: ```"shortform_autosuggest:VFB*^110.0 shortform_autosuggest:FBbt*^100.0 label_s:\"\"^2 synonym_s:\"\" short_form:FBbt_00003982^2 facets_annotation:Deprecated^0.001 facets_annotation:DataSet^100 facets_annotation:Deprecated^0.001" ```

The parameter setup is here https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/components/configuration/VFBMain/searchConfiguration.js#L86 

The actual name to use in the parameter vs name in the filter is from the key in https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/components/configuration/VFBMain/searchConfiguration.js#L182

**Comment by jrmartin** [comment]
Thanks @Robbie1977 , I understand now.
