### ISSUE TITLE
Role: User;  What: Run queries for neurons from ganglia; Why?  As for synaptic neuropil

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#124]
TODO: modify XMI to add queries used for synaptic neuropil to classes with label :Ganglion.

Example class: [GNG](http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00014013)

See VirtualFlyBrain/VFB_neo4j#18

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#80
