### ISSUE TITLE
V2 crashes when term info window is closed and model is clicked on

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/geppetto-vfb#126]
V2 crashes when the following sequence of events happens - term info window is closed then a highlighted structure on the model is clicked on (tested with lateral horn and antennal lobe). Site sometimes (about half the time) unfreezes after a minute or so, other times only a refresh fixes it.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#108
