### ISSUE TITLE
Circuit browser layout changes

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1263]
Changes to layout in the circuit browser:
- Wider boxes for the circuit browser
- 3 rows for the header
- 3 for the class name
- 1 row between header and content for the color stripe
- 3 rows for the content box down the header
- Color stripe instead of coloring the entire header
- Divide evenly the color stripe between all the colors that we need to display.
- Header and content should have the same height (45% header, 10% color stripe, 45% content), make this configurable if possible so it can be changed later on.

Questions:
- Can we center the text vertically if the class name/content is just one line?

Mockup:
- keep the same font type and size as now

![circ.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/dea79533-c1c6-4941-8a80-c96adadf2bd3)

**Comment by jrmartin** [comment]
@ddelpiano @Robbie1977 Few questions about this :

- For the colors bar, will there always be 3 different colors per node? 
- Same for the class and individual names, will it always be 3 of each per node?

Where do the 3 different colors, labels and individual names come from for each node? Currently each node only has 1 of each.

**Comment by Robbie1977** [comment]
@ddelpiano @jrmartin Can we make sure there is an equal 3 line space on either side of the colour bar as it currently looks like only 2 on the bottom. Just needs to be symmetrical with the colour bar in the centre vertically.
![image](https://user-images.githubusercontent.com/4630768/154075105-9f491543-b3b1-4e7f-bb7f-658c25db1c93.png)

**Comment by jrmartin** [comment]
@Robbie1977 Fix in progress for those last two issues, will have a PR open tomorrow.
