### ISSUE TITLE
Term context graph not correctly formatted

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1295]
Open https://v2-dev.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00016103&i=VFB_00101567,VFB_00009770,VFB_00011725,VFB_00015826,VFB_00016103

click on term context, the first graph will load fine
click on the hamburger icon on the left and select classification

![scrnli_14_02_2022_14-41-57.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/8794674b-1abf-4707-838f-c68ac42cbe74)

This is what the second graph look like.

![scrnli_14_02_2022_14-37-58.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/90582b02-d54d-4c62-b498-04a4efce7ca9)

**Comment by jrmartin** [comment]
Works now :
![image](https://user-images.githubusercontent.com/4562825/154578568-c0fc1a3e-d4ef-4534-b866-d230d5370f45.png)
