### ISSUE TITLE
Role: user; what: navigating through stack; why: to find/show content of interest

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#130]
UX testing found that users couldn't easily navigate through slice browser.  Didn't find two finger/ mouse wheel slice scroll; Didn't know where within stack they were; Didn't find the centre button (home icon).

Fixes:  
  1.  Faster tool tips
  2. Messages in top left need to be bigger.
  2. Using scroll buttons prompts tip  (top left) to use scroll with mouse/trackpad.  Also add this message as default on load.
  3. Easier to select content. 
  4. Auto-center stack to content when added.  (But need to add a lock to turn this off).
  5. Add slice slider bar  - needed for users accessing on tablets. (this also gives visual feedback of where you are in stack).
  6. Find nicer way to display slice locater on 3D viewer.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#112
