### ISSUE TITLE
increase text circuit browser

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1326]
- the text size of the nodes (header and content) should be configurable from the component json configuration
- if the text size in the cfg is set than that is the smallest text size the node should use, if strings are too long should cut them? @Robbie1977 

a plus for this card, it seems that the header is still bigger than the content (there was PR previously to fix this), could you please double check this did not get reverted by mistake/merge? Thx

**Comment by jrmartin** [comment]
This is how it looks now after making these changes. 

![Screenshot from 2022-04-07 14-54-01](https://user-images.githubusercontent.com/4562825/162332607-b036a6b4-5740-4037-9e3d-d84190af9825.png)
![Screenshot from 2022-04-07 14-44-13](https://user-images.githubusercontent.com/4562825/162332599-6ea8b956-3603-48e1-ac77-104582806e3f.png)
![Screenshot from 2022-04-07 14-39-32](https://user-images.githubusercontent.com/4562825/162332565-0693f02b-6421-4b09-9197-bdeb0cbee705.png)
