### ISSUE TITLE
Keep feature colour consistent on selection

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/geppetto-vfb#133]
Selecting a structure on the 3D model changes its colour - making it a less obvious to find the colour change icon since its colour no longer matches the colour on the 3D model
video here:
https://www.useloom.com/share/6273f747ed3f455796ec4a4807da00fc

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#114
