### ISSUE TITLE
Some semantic tags missing on Circuit browser

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#1345]
![Image](https://user-images.githubusercontent.com/112839/181033226-e8ba11a7-a7e1-493e-bdf9-e921386ea519.png)

Bottom right should have themosensory system

![Image](https://user-images.githubusercontent.com/112839/181033812-f393ba90-d751-4b6b-9326-c7e50791c86f.png)

Also: Thermosensory system needs a colour and 'adult + nervous system' should be stripped from circuit browser as not useful.

**Comment by dosumis** [comment]
STILL NEEDS FIXING - V.HIGH PRIORITY

**Comment by Robbie1977** [comment]
Fix added to dev (building) will be tested and pushed ASAP

**Comment by Robbie1977** [comment]
fix relased as part of v2.2.2.4
