### ISSUE TITLE
Missing images (vfb2-dev)

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#135]
![image](https://user-images.githubusercontent.com/112839/36339145-9717ca96-13b6-11e8-927e-3eaf8a4f874a.png)

Query for images only sparsely populated with actual images.

![image](https://user-images.githubusercontent.com/112839/36339155-c86d7a96-13b6-11e8-970b-ca861feb54ac.png)

**Comment by Robbie1977** [comment]
Pushing ahead with adding available images on in_register_with edge to replace on-load checking.

I'll add ```{nrrd,wlz,obj,swc,thumbnail}``` parameters to KB

Note: 
1) I did consider labelling by type e.g. slices (wlz) but this limits us in future as these may change, hence files extensions are more reliable except with thumbnail which could potentially be any html img format.
2) Scanning from real files to enable us to do some quick data sanity checking.

Then I'll reload pdb-dev.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#116
