### ISSUE TITLE
Type too general in table of painted (v2_dev)

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#136]
The table prompted by query for all painted domains on template displays the superclass of the domain type in the type column

![image](https://user-images.githubusercontent.com/112839/36339422-086df052-13bd-11e8-85b0-0c81a304577a.png)

Should be as for depicts here:

![image](https://user-images.githubusercontent.com/112839/36339731-fc9edece-13c3-11e8-83df-308b473d866a.png)

In Neo terms, given:

(anatomy:Individual)-[:INSTANCEOF]->(x:Class)->[:SUBCLASSOF]->(y:Class)

The table is displaying y when it should be displaying x

In contrast, the type column in this list of images displays the direct type (x):

![image](https://user-images.githubusercontent.com/112839/36339447-0e018884-13be-11e8-9804-62818c79c7c9.png)

**Comment by Robbie1977** [comment]
Query here: https://github.com/VirtualFlyBrain/VFB2/blob/dev/html/conf/vfb.xmi#L199

**Comment by Robbie1977** [comment]
Replacing with:
```MATCH (n:Template {short_form:'VFB_00017894'})<-[:depicts]-(:Template)<-[r:in_register_with]-(dc:Individual)-[:depicts]->(di:Individual)-[:INSTANCEOF]->(d:Class) WHERE has(r.index) RETURN distinct di.short_form as id, di.label as name, d.description[0] as def, COLLECT(DISTINCT d.label) as type, replace(r.iri,'http:','https:') + '/thumbnailT.png' AS file```

**Comment by Robbie1977** [comment]
Also taking the individual description if one exists: 
```MATCH (n:Template {short_form:'VFB_00017894'})<-[:depicts]-(:Template)<-[r:in_register_with]-(dc:Individual)-[:depicts]->(di:Individual)-[:INSTANCEOF]->(d:Class) WHERE has(r.index) RETURN distinct di.short_form as id, di.label as name, coalesce(di.description[0],d.description[0]) as def, COLLECT(DISTINCT d.label) as type, replace(r.iri,'http:','https:') + '/thumbnailT.png' AS file```
