### ISSUE TITLE
Missing references!

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#142]
Reference section misses references.  Just has a link to FlyBase

e.g. 

![image](https://user-images.githubusercontent.com/112839/37242739-664a51ca-2466-11e8-8612-3c48de3c562a.png)

![image](https://user-images.githubusercontent.com/112839/37242714-1528961c-2466-11e8-8860-d2da20381a5a.png)

Should have:

![image](https://user-images.githubusercontent.com/112839/37242731-5a8da7f6-2466-11e8-9d3d-eb3697387c80.png)

**Comment by Robbie1977** [comment]
@dosumis This is a general issue as references seem to not be added as before in the new pipeline

**Comment by Robbie1977** [comment]
It's expecting the FB pub node to have a 'miniref'

**Comment by Robbie1977** [comment]
Only 1 node in the KB has this anymore?
```MATCH (n:pub) where exists(n.miniref) RETURN n LIMIT 25```
```{
  "iri": "https://doi.org/10.1101/198648",
  "miniref": "Tirian & Dickson 2017",
  "DOI": "10.1101/198648"
}```

**Comment by Robbie1977** [comment]
Spotted the issue in the pipeline:
```
python3 /opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/import_pub_data.py http://192.168.0.2:7474 neo4j vfb
Traceback (most recent call last):
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/import_pub_data.py", line 2, in <module>
    from uk.ac.ebi.vfb.neo4j.flybase2neo.dbtools import dict_cursor, get_fb_conn
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/flybase2neo/dbtools.py", line 25
    sgml_string = re.sub('<\\\up>', ']', sgml_string)
                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: truncated \uXXXX escape
```

**Comment by dosumis** [comment]
Fixed (actually fixed last week in a branch but git screw up meant old version of file was hanging around after rename).

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#117
