### ISSUE TITLE
Text case mangled in results tables

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#15]
The case is fine in the neo4J DB.  There's no reason for it to be all shifted to lowercase here:

![image](https://cloud.githubusercontent.com/assets/112839/25243485/141d09c6-25f5-11e7-9b49-bdda3f0154db.png)

Captialization at the start of sentences and for names is gone, as is capitalization of abbreviations in names (DC2 adPN not dc2 adpn).

In general, no text in the DB should be changed for presentation, e.g. encoding as unicode is all set correctly in the DB.

**Comment by Robbie1977** [comment]
fixed
