### ISSUE TITLE
Create wire frame mockup of new layout, inc new header, sub-windows, internal tabs

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#152]
- [x] Review UX suggestions
- [x] Resolve search/query
- [x] Add tabs for templates
- [x] Redesign top bar and menu
- [x] Resolve tooltips
- [x] Add search results
- [x] Resolve slice viewer interface problems (slider)
- [x] Show gross types
- [x] Make focused term obvious
- [x] Make citation window available from a prominent spot
- [x] Every window should have an X to close it
- [x] Add dialog before switching to a template with an option to hide the message in the future

**Comment by tarelli** [comment]
Work in progress: https://wireframepro.mockflow.com/view/Mf9b9c133a2689c0a89fedb302ff30a211526990565339#/page/44ef6eb288664302ae241d0c7c2f0169
