### ISSUE TITLE
Document current NBLAST API

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#156]

**Comment by tarelli** [comment]
@Robbie1977 can you pop in an estimate for this?

**Comment by Robbie1977** [comment]
label based query doc here: http://jefferis.github.io/flynblastscores/reference/flycircuit_topn.html

Our API is: http://r.virtualflybrain.org/ocpu/ 
Example query:
![image](https://user-images.githubusercontent.com/4630768/41542784-aea53368-730d-11e8-9a51-edd120fb554f.png)

query="label" Note: this will be query="$ID"
n=0 will return all results when updated.

**Comment by Robbie1977** [comment]
New function:
http://jefferis.github.io/vfbr/reference/vfb_nblast.html

**Comment by Robbie1977** [comment]
![image](https://user-images.githubusercontent.com/4630768/41719356-ba873b94-7557-11e8-9a36-e83f51fbcc81.png)
