### ISSUE TITLE
Design and implement NBLAST results table

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#158]

**Comment by ddelpiano** [comment]
@Robbie1977 @dosumis does the results table have to change or will stay the same?
What NBLAST will return as result of a query? Thx

**Comment by ddelpiano** [comment]
![Screenshot from 2018-06-29 14-34-38.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/8e332f5a-f982-4563-9001-d91e94a043f9)
