### ISSUE TITLE
Declarative specification for term info

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#161]

**Comment by ddelpiano** [comment]
- Widget capability to be used as external wrapped
- GeppettoModelViewer (GMV) component generic to visualize the metadata’s model
- GMV will define:
-- order of the visual element (e.g.:  props={order:[“references’“, “asdas”,“thumbnails”]}
-- nested react component to be used (toolbar for example) (e.g.: props={toolbar={toolBarConfiguration}} ).
-- instance to be visualized (e.g.:props={model: {VFB_00017894.VFB_00017894_meta}} ).
- Backend will not require any change.
