### ISSUE TITLE
Define query results specification

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#162]
MetaCell needs a general spec for the types of columns we need to support.

rough draft

 - single image *
e.g. 
![image](https://user-images.githubusercontent.com/112839/48076421-0e601500-e1dd-11e8-8f83-13a773b84ffd.png)
 - image browser *
    e.g. 
![image](https://user-images.githubusercontent.com/112839/48076372-f6889100-e1dc-11e8-98bc-945174b2f403.png)
-  plain text
-  single hyperlinked text entity
e.g. 
![image](https://user-images.githubusercontent.com/112839/48076565-5c751880-e1dd-11e8-87a8-19b171c7f7e8.png)
-  list of hyperlinked text items
 e.g. list of supporting pubs.  We don't have this yet.
-  number (int/float etc)
e.g. 
![image](https://user-images.githubusercontent.com/112839/48076665-921a0180-e1dd-11e8-8536-c130a5e98400.png)

* both are supported by the current 'images' column

**Comment by Robbie1977** [comment]
We have agreed the above will work we also need to keep in mind the conversion to CSV.

**Comment by tarelli** [comment]
@Robbie1977 @dosumis epic estimated see [here](https://app.zenhub.com/workspaces/59c292c4286ea849ed3c9326/issues/virtualflybrain/geppetto-vfb/164) we can review together on Monday

![Screenshot 2019-02-21 at 12.50.16.png](https://images.zenhubusercontent.com/53cfecb449f8b7fd7f00149b/0da6a3c4-a1cb-43d7-b7bd-7e100dcfd5d3)

**Comment by dosumis** [comment]
Need to discuss on Monday - but I'd say this is a higher priority than Menus as it is required for a full release of VFB2 -  recapitulating queries in VFB 1.5.  Without this we can't really give users easy ways to find all of the cool new driver images we have when starting from anatomy - this is pretty fundamental to core VFB use cases.

**Comment by dosumis** [comment]
Menus, otoh, just redistribute existing functionality from buttons and TermInfo queries.

**Comment by gidili** [comment]
@dosumis let's discuss on monday but [SPOILER ALERT] menus are already done and working 😄
