### ISSUE TITLE
Decide on JS framework for interactive graph display from D3 JSON

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#165]
See mockups in jsfiddle -  @dosumis @Robbie1977  to update and post.

**Comment by Robbie1977** [comment]
ideas: https://github.com/d3/d3/wiki/Gallery

**Comment by ddelpiano** [comment]
2D versions:
https://vasturiano.github.io/force-graph/example/tree/
https://vasturiano.github.io/force-graph/example/medium-graph/
https://eisman.github.io/neo4jd3/

3D versions:
https://vasturiano.github.io/3d-force-graph/example/tree/
https://vasturiano.github.io/3d-force-graph/example/large-graph/

With the 3d/2d Vasturiano's library the type represented can be different, there are different examples that show text, images, etc.
