### ISSUE TITLE
Create contextual graph browser

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#170]

**Comment by ddelpiano** [comment]
Context browser - connected graph starting from one root (a bottom) = focus term - graph laid out above. Folding/unfolding not needed. Graphs are generated in response to one of a small number of queries about focus term: what is it? where is it? What does it develop from? Need to think about how query component fits into flow. 3D is not needed at present - but happy to have it as an option.
(from @dosumis from the card https://app.zenhub.com/workspaces/vfb15-59c292c4286ea849ed3c9326/issues/virtualflybrain/geppetto-vfb/337 )

**Comment by dosumis** [comment]
Layout - QuickGO solves layout for these types of context graphs nicely:

![image](https://user-images.githubusercontent.com/112839/60825320-5b005380-a1a3-11e9-8c09-6f5c411bd263.png) (https://www.ebi.ac.uk/QuickGO/term/GO:0097189)

**Comment by dosumis** [comment]
Draft Cypher queries.

What is X: 

```cql
MATCH p=(n:Class)-[:SUBCLASSOF*..]->(x) 
WHERE (('Cell' IN  labels(x)) or ('synaptic neuropil' IN labels(x))) 
AND n.short_form = 'FBbt_00003686' return  p
```

short_form here = focus term.    Restrictions on labels probably need work to be universally applicable.
