### ISSUE TITLE
Create connectome explorer

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#171]

**Comment by ddelpiano** [comment]
Circuit explorer - connected graph organised in columns. Would be good to be able to display edge strength as thickness. Graphs are generated from two leg queries => starting entity class or individual & ending entity class or individual + specification of max number of links. Column position determined by simple algorithm we provide. We need to be able to colour render nodes by type (Neo4J label / Geppetto model supertype).
(from @dosumis from the card https://app.zenhub.com/workspaces/vfb15-59c292c4286ea849ed3c9326/issues/virtualflybrain/geppetto-vfb/337 )

**Comment by dosumis** [comment]
Component 3: Circuit explorer - connected graph organised in columns.  Would be good to be able to display  edge strength as thickness.  Graphs are  generated from two leg queries => starting entity class or individual & ending entity  class or individual  + specification of max number of links.  Column position determined by simple algorithm we provide.  We need to be able to colour render nodes by type (Neo4J label / Geppetto model supertype).

**Comment by dosumis** [comment]
Description of graphs:

- The graph is directed, but not necessarily acyclic
- There is a single start node and 1-many end (target) nodes.

Layout/rendering specs:

- Nodes are ordered into columns (vertical position in column has no semantics)
- columns (spec using python array slice syntax - 0 = first column -1 = last)
     - column[0] = start node S;  
     - column[-1] = end node(s) E;
     - column[n] = all nodes n steps away from the starting node (S) by the shortest path.  (Any node may also be > n steps away by other paths.  This is not relevant to the choice of column).
- Edge thickness should be drive-able by numeric edge properties (including but not limited to synapse number - not necessary for MVP?)
- by default - start node is on left, end node(s) are on right

Interactions:
- Nodes should be selectable => focus term
- Edge properties should be visible on float-over (Not necessary for MVP)

Performance:
- Calculation of ordering needs to be rapid (10s-100s ms).  
- It is reasonable to set an upper limit on the size of the graph that can displayed both for speed and ease of use.

Some notes:

1. The possible presence of cycles may make this challenging. 
2. It is entirely possible, given this spec, that definitive specification of node position is not possible for some nodes.  This is OK.  The tool will be perfectly usable if ordering is semi-arbitrary for edge/corner cases 

Simple example (hand ordered from Neo4J graph). Note cycle.  (Also note - differs from spec in that start is on right)

![image](https://user-images.githubusercontent.com/112839/60821826-3a80cb00-a19c-11e9-8d3e-780b91c6e09f.png)

**Comment by dosumis** [comment]
Some draft queries:

This produces the above graph - but the second restriction on this only works by neo:label - probably not sufficient for most use cases.

```cql
MATCH p=(n:Class)<-[:synapsed_to*..3]-(x:Sensory_neuron)
WHERE n.short_form = 'FBbt_00002303' return  p
```

Rewritten using a class restriction:

```cql
MATCH (y:Class)-[:SUBCLASSOF*]->(x:Class) 
WHERE x.short_form = 'FBbt_00005124' 
WITH collect(y.short_form) + [x.short_form] as sc MATCH p=(n:Class)<-[:synapsed_to*..3]-(y:Class) 
WHERE n.short_form = 'FBbt_00002303' AND y.short_form in sc return  p
```
