### ISSUE TITLE
Lockup on spotlight

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#18]
Opening cluster from spotlight is failing
![image](https://cloud.githubusercontent.com/assets/4630768/25280514/24d17c22-26a2-11e7-9564-28835eb7ad70.png)

**Comment by Robbie1977** [comment]
@dosumis we went back and forth on this one. 
When opening I can either treat clusters as:
1) a class and simply display info
2) display the exemplar for the cluster
3) add all members
Which is your preference?

**Comment by dosumis** [comment]
The display I've been seeing for specific clusters on 2a looks good apart from lacking exemplar type.  Should be:  Image = whole cluster.  Exemplar Type (depicts) prominently displayed + exemplar relationships. Members should be accessed by query, not listed.

Hope this is clear enough
