### ISSUE TITLE
Caps lost in name and definitions in query

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#191]
@mmc46 commented on [Fri Mar 02 2018](https://github.com/VirtualFlyBrain/VFB2/issues/27)

![caps_issue](https://user-images.githubusercontent.com/1872083/36907346-5409aa6a-1e30-11e8-9af1-32923e1250cb.png)
Query for adult antennal lobe. From there choose

'Query for: Neurons with synaptic terminals in adult antennal lobe'
Caps lost: 
Name: 'adult antennal lobe projection neuron adpn' should be 'adult antennal lobe projection neuron adPN'

Definition:'An adult antennal lobe projection neuron that is derived from neuroblast alad1 (fbbt:00067346). all of these neurons have axons that fasciculate with the medial antennal lobe tract (malt) and innervate the lateral horn' should be 'An adult antennal lobe projection neuron that is derived from neuroblast ALad1 (FBbt:00067346). All of these neurons have axons that fasciculate with the medial antennal lobe tract (mALT) and innervate the lateral horn.

See screenshot for other examples.

---

@Robbie1977 commented on [Mon Mar 05 2018](https://github.com/VirtualFlyBrain/VFB2/issues/27#issuecomment-370397061)

Caused by reinstated capitalisation with new less formatting:  https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.less#L457

---

@Robbie1977 commented on [Mon Mar 05 2018](https://github.com/VirtualFlyBrain/VFB2/issues/27#issuecomment-370432651)

Still name being lowercased - need to track down code (not CSS)

---

@Robbie1977 commented on [Tue May 22 2018](https://github.com/VirtualFlyBrain/VFB2/issues/27#issuecomment-390966356)

Still an issue for ```name``` and ```definition``` columns

**Comment by ddelpiano** [comment]
Hi @Robbie1977 , I played a bit with this but it seems that aberOWL is returning the lowercase string, attached screenshot with walk through in debug mode.                     
![adpn.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/999b7ed7-90c1-42a6-a435-f4a0dacedd4f)

**Comment by Robbie1977** [comment]
This isn't worth fixing in AberOWL.
We need to modify to allow Neo to fill name and definition as Owlery won't give this anyway.
Example query above:
https://github.com/VirtualFlyBrain/VFB2/blob/dev/html/conf/vfb.xmi#L476
AberOWL Process step here: 
https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/development/src/main/java/uk/ac/vfb/geppetto/VFBAberOWLQueryProcessor.java
Neo processor after: 
https://github.com/VirtualFlyBrain/VFB2/blob/dev/html/conf/vfb.xmi#L119
https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/development/src/main/java/uk/ac/vfb/geppetto/CreateImagesForQueryResultsQueryProcessor.java

**Comment by Robbie1977** [comment]
Issue moved to [VirtualFlyBrain/VFB2 #120](https://github.com/VirtualFlyBrain/VFB2/issues/120) via [**ZenHub**](https://www.zenhub.com/)
