### ISSUE TITLE
Responsive tooltips on slice viewer hover

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#198]
- [ ] Turn label into tooltip
- [ ] Improve speed of the tooltip appearance

**Comment by tarelli** [comment]
This is not about refactoring the Stack Viewer, rather trying to improve how quick the label appears.

**Comment by Robbie1977** [comment]
```hoverTime``` is used to identify when someone is truly hovering the delay is set here: https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js#L972
