### ISSUE TITLE
Search should support multiple options for restriction

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#205]
Assume this refers to adding support making choice of what to search?  Search-all is becoming way too ungainly as content grows. 

BTW - Thought there was another, more detailed ticket on this - added after the project meeting in September - but I've failed to find it.

**Comment by dosumis** [comment]
What options should we support?

There are good cases for:

- all vs larva vs adult  
- all vs nervous system
- all vs anatomy vs images

Each of these choices on their own make sense as a choice between 3 options, but choice between the three elements on this list does not - An image may be of a piece of adult neuro-anatomy, a piece of non-neural anatomy from the larva etc...


UI dev: 
Having a set of overlapping choices fits best with radio buttons.  Is there a modern elegant way to do these? - something that doesn't look like a hangover from the 90s?
One possibility: 
https://www.ebi.ac.uk/ols/ontologies/duo
![image](https://user-images.githubusercontent.com/112839/72349239-07cc0800-36d4-11ea-8b62-97aeea105d6b.png)
Uses icheck-bootstrap

Back End: 

SOLR indexes
Geppetto hooks for SOLR indexes (through XMI?)

**Comment by dosumis** [comment]
Some precedent:

![image](https://user-images.githubusercontent.com/112839/72821242-25ffae00-3c68-11ea-8c7b-77cf300b0625.png)

**Comment by dosumis** [comment]
New spec:


Set of simple filters.  No  filters selected => all displayed.  choosing a filter => filtering by that tag.  Multiple filters are OR.  

Complicating factor: some things are neither larva nor adult.  Need stage neutral option?
