### ISSUE TITLE
Term info disappears when escaping out of query

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#21]
open query from term info then press esc to exit results and term info 'disappears' but isn't closed.

**Comment by Robbie1977** [comment]
to replicate open https://v2a.virtualflybrain.org/ click 'List all painted anatomy available for JFRC2_template' both query and Trem info closes.

**Comment by jrmartin** [comment]
This commit takes care of it . Tested locally and not there anymore
https://github.com/openworm/org.geppetto.frontend/commit/2ecaae222136e1ba4a4a3cbbef2098fc24877550

**Comment by Robbie1977** [comment]
Tested on https://v2a.virtualflybrain.org/
