### ISSUE TITLE
Review wire frame mockup for new VFB layout 

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#216]

**Comment by ddelpiano** [comment]
https://wireframepro.mockflow.com/view/Mf9b9c133a2689c0a89fedb302ff30a211526990565339#/page/44ef6eb288664302ae241d0c7c2f0169

**Comment by Robbie1977** [comment]
@ddelpiano the <Show menu has disappeared and as a consequence Remove from Scene now opens the 'Query' menu.

I've added a comment on the browser does this work OK as a form of feedback?

**Comment by ddelpiano** [comment]
@Robbie1977 that works for us, thanks for the spot, will fix it soon.
