### ISSUE TITLE
Owlery not handling results

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#229]
Fails on all but test for subclasses of the medulla (FBbt_00003748)

owlery query:
```
http://owl.virtualflybrain.org/kbs/vfb/subclasses?object=%3Chttp://purl.obolibrary.org/obo/BFO_0000050%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003748%3E&amp;direct=false&amp;includeDeprecated=false&amp;includeEquivalent=true
```

virgo log.log:
```
05/07/2018 12:55:54[2018-07-05 11:55:54.399] ERROR http-bio-8080-exec-4         org.apache.coyote.http11.Http11Protocol                           Error reading request, ignored java.lang.NullPointerException: null
05/07/2018 12:55:54	at org.geppetto.datasources.owlery.OWLeryResponseProcessor.processResponse(OWLeryResponseProcessor.java:37)
05/07/2018 12:55:54	at org.geppetto.datasources.ExecuteQueryVisitor.processResponse(ExecuteQueryVisitor.java:228)
05/07/2018 12:55:54	at org.geppetto.datasources.ExecuteQueryVisitor.caseSimpleQuery(ExecuteQueryVisitor.java:196)
05/07/2018 12:55:54	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:116)
05/07/2018 12:55:54	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
05/07/2018 12:55:54	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
05/07/2018 12:55:54	at org.geppetto.datasources.ExecuteQueryVisitor.caseCompoundRefQuery(ExecuteQueryVisitor.java:140)
05/07/2018 12:55:54	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:136)
05/07/2018 12:55:54	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
05/07/2018 12:55:54	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
05/07/2018 12:55:54	at org.geppetto.datasources.ExecuteMultipleQueriesVisitor.caseRunnableQuery(ExecuteMultipleQueriesVisitor.java:72)
05/07/2018 12:55:54	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:153)
05/07/2018 12:55:54	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
05/07/2018 12:55:54	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
05/07/2018 12:55:54	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:25)
05/07/2018 12:55:54	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:72)
05/07/2018 12:55:54	at org.geppetto.datasources.ADataSourceService.getNumberOfResults(ADataSourceService.java:70)
05/07/2018 12:55:54	at org.geppetto.simulation.manager.RuntimeProject.runQueryCount(RuntimeProject.java:429)
05/07/2018 12:55:54	at org.geppetto.simulation.manager.GeppettoManager.runQueryCount(GeppettoManager.java:880)
05/07/2018 12:55:54	at org.geppetto.frontend.controllers.ConnectionHandler.runQueryCount(ConnectionHandler.java:495)
05/07/2018 12:55:54	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:459)
05/07/2018 12:55:54	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:78)
05/07/2018 12:55:54	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
05/07/2018 12:55:54	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
05/07/2018 12:55:54	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
05/07/2018 12:55:54	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:616)
05/07/2018 12:55:54	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
05/07/2018 12:55:54	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
05/07/2018 12:55:54	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
05/07/2018 12:55:54	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
05/07/2018 12:55:54	at java.lang.Thread.run(Thread.java:745)
05/07/2018 12:55:54
```

**Comment by Robbie1977** [comment]
```@context```
Has changed in latest owlery version:

```{"@id":"_:b0","value":"ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/FBbt_00003748>)","superClassOf":["http://purl.obolibrary.org/obo/FBbt_00111271","http://purl.obolibrary.org/obo/FBbt_00111071","http://purl.obolibrary.org/obo/FBbt_00111273","http://purl.obolibrary.org/obo/FBbt_00003774","http://purl.obolibrary.org/obo/FBbt_00003832","http://purl.obolibrary.org/obo/FBbt_00111267","http://purl.obolibrary.org/obo/FBbt_00111364","http://purl.obolibrary.org/obo/FBbt_00003834","http://purl.obolibrary.org/obo/FBbt_00003768","http://purl.obolibrary.org/obo/FBbt_00045002","http://purl.obolibrary.org/obo/FBbt_00003770","http://purl.obolibrary.org/obo/FBbt_00110986","http://purl.obolibrary.org/obo/FBbt_00110090","http://purl.obolibrary.org/obo/FBbt_00003772","http://purl.obolibrary.org/obo/FBbt_00110988","http://purl.obolibrary.org/obo/FBbt_00111076","http://purl.obolibrary.org/obo/FBbt_00003756","http://purl.obolibrary.org/obo/FBbt_00100528","http://purl.obolibrary.org/obo/FBbt_00110076","http://purl.obolibrary.org/obo/FBbt_00111078","http://purl.obolibrary.org/obo/FBbt_00003758","http://purl.obolibrary.org/obo/FBbt_00110078","http://purl.obolibrary.org/obo/FBbt_00111080","http://purl.obolibrary.org/obo/FBbt_00003760","http://purl.obolibrary.org/obo/FBbt_00111072","http://purl.obolibrary.org/obo/FBbt_00111282","http://purl.obolibrary.org/obo/FBbt_00003752","http://purl.obolibrary.org/obo/FBbt_00005738","http://purl.obolibrary.org/obo/FBbt_00111074","http://purl.obolibrary.org/obo/FBbt_00003754","http://purl.obolibrary.org/obo/FBbt_00111066","http://purl.obolibrary.org/obo/FBbt_00111276","http://purl.obolibrary.org/obo/FBbt_00111268","http://purl.obolibrary.org/obo/FBbt_00110066","http://purl.obolibrary.org/obo/FBbt_00111068","http://purl.obolibrary.org/obo/FBbt_00111278","http://purl.obolibrary.org/obo/FBbt_00111270","http://purl.obolibrary.org/obo/FBbt_00110134","http://purl.obolibrary.org/obo/FBbt_00110068","http://purl.obolibrary.org/obo/FBbt_00013774","http://purl.obolibrary.org/obo/FBbt_00111070","http://purl.obolibrary.org/obo/FBbt_00111280","http://purl.obolibrary.org/obo/FBbt_00003750","http://purl.obolibrary.org/obo/FBbt_00111272","http://purl.obolibrary.org/obo/FBbt_00110989","http://purl.obolibrary.org/obo/FBbt_00111274","http://purl.obolibrary.org/obo/FBbt_00111363","http://purl.obolibrary.org/obo/FBbt_00003833","http://purl.obolibrary.org/obo/FBbt_00003767","http://purl.obolibrary.org/obo/FBbt_00110095","http://purl.obolibrary.org/obo/FBbt_00045001","http://purl.obolibrary.org/obo/FBbt_00111365","http://purl.obolibrary.org/obo/FBbt_00003835","http://purl.obolibrary.org/obo/FBbt_00003769","http://purl.obolibrary.org/obo/FBbt_00045003","http://purl.obolibrary.org/obo/FBbt_00003771","http://purl.obolibrary.org/obo/FBbt_00110987","http://purl.obolibrary.org/obo/FBbt_00110091","http://purl.obolibrary.org/obo/FBbt_00003773","http://purl.obolibrary.org/obo/FBbt_00111077","http://purl.obolibrary.org/obo/FBbt_00003757","http://purl.obolibrary.org/obo/FBbt_00111279","http://purl.obolibrary.org/obo/FBbt_00003749","http://purl.obolibrary.org/obo/FBbt_00110077","http://purl.obolibrary.org/obo/FBbt_00110135","http://purl.obolibrary.org/obo/FBbt_00111079","http://purl.obolibrary.org/obo/FBbt_00110069","http://purl.obolibrary.org/obo/FBbt_00003759","http://purl.obolibrary.org/obo/FBbt_00111281","http://purl.obolibrary.org/obo/FBbt_00003751","http://purl.obolibrary.org/obo/FBbt_00110079","http://purl.obolibrary.org/obo/FBbt_00111073","http://purl.obolibrary.org/obo/FBbt_00003753","http://purl.obolibrary.org/obo/FBbt_00110081","http://purl.obolibrary.org/obo/FBbt_00111275","http://purl.obolibrary.org/obo/FBbt_00111075","http://purl.obolibrary.org/obo/FBbt_00003755","http://purl.obolibrary.org/obo/FBbt_00111067","http://purl.obolibrary.org/obo/FBbt_00111277","http://purl.obolibrary.org/obo/FBbt_00110075","http://purl.obolibrary.org/obo/FBbt_00111269","http://purl.obolibrary.org/obo/FBbt_00110133","http://purl.obolibrary.org/obo/FBbt_00110067","http://purl.obolibrary.org/obo/FBbt_00111069"],"@context":"https://owlery.phenoscape.org/json/context.jsonld"}``` 

https://owlery.phenoscape.org/json/context.jsonld 
now contains:
```
{
  "@context": {
    "equivalentClass": {
      "@id": "http://www.w3.org/2002/07/owl#equivalentClass",
      "@type": "@id"
    },
    "subClassOf": {
      "@id": "http://www.w3.org/2000/01/rdf-schema#subClassOf",
      "@type": "@id"
    },
    "superClassOf": {
      "@reverse": "http://www.w3.org/2000/01/rdf-schema#subClassOf",
      "@type": "@id"
    },
    "type": "@type",
    "hasInstance": {
      "@reverse": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
      "@type": "@id"
    },
    "isSatisfiable": {
      "@id": "http://purl.org/phenoscape/owlery.owl#isSatisfiable",
      "@type": "http://www.w3.org/2001/XMLSchema#boolean"
    },
    "value": {
      "@id": "http://www.w3.org/1999/02/22-rdf-syntax-ns#value"
    }
  }
}
```

**Comment by Robbie1977** [comment]
@ddelpiano need to step through and see where it's failing as keys hardwired ( https://github.com/openworm/org.geppetto.datasources/blob/feature/owlery_integration/src/main/java/org/geppetto/datasources/owlery/OWLeryResponseProcessor.java#L32) so should work but is failing here https://github.com/openworm/org.geppetto.datasources/blob/feature/owlery_integration/src/main/java/org/geppetto/datasources/owlery/OWLeryResponseProcessor.java#L37

**Comment by Robbie1977** [comment]
I think this might be the issue as fixed in nblast branch:
https://github.com/openworm/org.geppetto.datasources/commit/d1364953d6949b68809b390563017a3db83c5fdb

**Comment by Robbie1977** [comment]
@ddelpiano still happening on latest development branch:
```
05/07/2018 14:58:37[2018-07-05 13:58:37.182] ERROR http-bio-8080-exec-6         org.apache.coyote.http11.Http11Protocol                           Error reading request, ignored java.lang.NullPointerException: null
05/07/2018 14:58:37	at org.geppetto.datasources.owlery.OWLeryResponseProcessor.processResponse(OWLeryResponseProcessor.java:35)
05/07/2018 14:58:37	at org.geppetto.datasources.ExecuteQueryVisitor.processResponse(ExecuteQueryVisitor.java:238)
05/07/2018 14:58:37	at org.geppetto.datasources.ExecuteQueryVisitor.caseSimpleQuery(ExecuteQueryVisitor.java:196)
05/07/2018 14:58:37	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:116)
05/07/2018 14:58:37	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
05/07/2018 14:58:37	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
05/07/2018 14:58:37	at org.geppetto.datasources.ExecuteQueryVisitor.caseCompoundRefQuery(ExecuteQueryVisitor.java:140)
05/07/2018 14:58:37	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:136)
05/07/2018 14:58:37	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
05/07/2018 14:58:37	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
05/07/2018 14:58:37	at org.geppetto.datasources.ExecuteMultipleQueriesVisitor.caseRunnableQuery(ExecuteMultipleQueriesVisitor.java:72)
05/07/2018 14:58:37	at org.geppetto.model.datasources.util.DatasourcesSwitch.doSwitch(DatasourcesSwitch.java:153)
05/07/2018 14:58:37	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
05/07/2018 14:58:37	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
05/07/2018 14:58:37	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:25)
05/07/2018 14:58:37	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:72)
05/07/2018 14:58:37	at org.geppetto.datasources.ADataSourceService.getNumberOfResults(ADataSourceService.java:70)
05/07/2018 14:58:37	at org.geppetto.simulation.manager.RuntimeProject.runQueryCount(RuntimeProject.java:429)
05/07/2018 14:58:37	at org.geppetto.simulation.manager.GeppettoManager.runQueryCount(GeppettoManager.java:880)
05/07/2018 14:58:37	at org.geppetto.frontend.controllers.ConnectionHandler.runQueryCount(ConnectionHandler.java:495)
05/07/2018 14:58:37	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:459)
05/07/2018 14:58:37	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:78)
05/07/2018 14:58:37	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
05/07/2018 14:58:37	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
05/07/2018 14:58:37	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
05/07/2018 14:58:37	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:616)
05/07/2018 14:58:37	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
05/07/2018 14:58:37	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
05/07/2018 14:58:37	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
05/07/2018 14:58:37	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
05/07/2018 14:58:37	at java.lang.Thread.run(Thread.java:745)
05/07/2018 14:58:37
```

**Comment by ddelpiano** [comment]
@Robbie1977 i guess the issue we discussed was part of this card as well, I let you move this to the review/done as soon you are ok with the new xmi.
Thanks
