### ISSUE TITLE
ensuring oCPU API is expandable for all uses

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#232]
we need to ensure all NBLAST queries can be added (different target settings) as well as any future R requirements, Hence I suggest the following changes:

https://github.com/openworm/org.geppetto.datasources/blob/feature/nblast_intergration/change1/src/main/resources/templates/OpenCPU/queryTemplate.vm#L2

https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/feature/nblast_integration/src/test/resources/VFBModel/GeppettoModelVFB.xmi#L428

**Comment by Robbie1977** [comment]
@ddelpiano can you check you're happy with the changes

**Comment by ddelpiano** [comment]
@Robbie1977  that's fine for me, thx
