### ISSUE TITLE
Results table overlaping

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#242]
See:
![image](https://user-images.githubusercontent.com/4630768/43959343-6262b4ae-9ca6-11e8-982e-9a944a4c28f7.png)

Noticed on: https://v2-dev.virtualflybrain.org/?i=VFB_00017894
running off development branches

**Comment by gidili** [comment]
Probably a result of adding the new field compressed the other columns?

**Comment by Robbie1977** [comment]
@gidili is there no fixed border triggering wrapping?

**Comment by gidili** [comment]
@Robbie1977 I would have expected so, but maybe it was removed it to avoid some other behaviour somewhere along the line, need to have a proper look

**Comment by Robbie1977** [comment]
```#querybuilder .griddle table{
    table-layout: auto important;
}```
should fix it - just testing

**Comment by Robbie1977** [comment]
fixed for VFB but might want to have auto as the default in your CSS
