### ISSUE TITLE
Selection is very glitchy

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#243]
https://v2.virtualflybrain.org/?i=VFB_00017894,VFB_00002001,VFB_00022673,VFB_00021534

Changing selection is not working for me (once a few items are added) in chrome.

**Comment by ddelpiano** [comment]
@Robbie1977 was this in the same scope of the 3 bugs fixed by Jesus?
In case I will move this to the done column.
Thanks.

**Comment by Robbie1977** [comment]
I will raise a better ticket if it's still an issue.
