### ISSUE TITLE
feature/react_refactoring: can't combine i & id

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#253]
multiple url parameters don't seem to be handled as i=VFB_xxxxxxxx&id=VFB_yyyyyyyy is resulting in 'VFB_xxxxxxxx&id=VFB_yyyyyyyy' trying to be loaded

**Comment by ddelpiano** [comment]
https://github.com/VirtualFlyBrain/geppetto-vfb/commit/9f8e46af9c60ecc2c7ddb6cd81cc5a3020794dda
