### ISSUE TITLE
feature/react_refactoring: terminfo button bar not updating on change

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#259]
Selection and visibility (probably also colour) icons failing to update when changes made via canvas or control panel.

Ref #249

**Comment by ddelpiano** [comment]
@Robbie1977 I can see this working fine both locally and on v2-dev, 2 screenshot, the first once VFB is loaded, the second with all the buttons clicked once. 

![screenshot from 2018-10-04 02-50-10](https://user-images.githubusercontent.com/37704177/46448747-617b1e00-c780-11e8-967d-03bcca68bd0b.png)
![screenshot from 2018-10-04 02-51-48](https://user-images.githubusercontent.com/37704177/46448773-7952a200-c780-11e8-9440-d840c455bb6e.png)

**Comment by Robbie1977** [comment]
Again has been fixed now
