### ISSUE TITLE
Deleting an entity from the viewers only deletes from 3D canvas, not stack browser

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#26]
e.g. in this scene, the fan-shaped body has been dropped from the control panel.  It no longer shows on the 3D canvas but is still labelled in the stack browser:

![image](https://cloud.githubusercontent.com/assets/112839/25667632/f80d4f4e-301b-11e7-8072-ee4847093270.png)

**Comment by dosumis** [comment]
Console: 
Instance created...
main.bundle.js:97 Adding FB - painted domain JFRC2 to 2
main.bundle.js:97 Passing 3 instances
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 Passing instance: VFB_00030633
main.bundle.js:116 An import type has been resolved to a full type and swapped into the Geppetto model: 93.27001953125ms
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 Colour change...
main.bundle.js:97 Adding FB - painted domain JFRC2 to 3
main.bundle.js:97 Passing 3 instances
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 Colour change...
main.bundle.js:97 Adding FB - painted domain JFRC2 to 3
main.bundle.js:97 Passing 3 instances
main.bundle.js:96 unmount
4/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 Updating stack...
main.bundle.js:98 fan-shaped body clicked
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 VFB_00030633 deleted...
main.bundle.js:97 Removing VFB_00030633 from 3
main.bundle.js:97 Passing 2 instances
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 VFB_00030633 deleted...
main.bundle.js:97 Removing VFB_00030633 from 2
main.bundle.js:97 Passing 2 instances
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 VFB_00030633 deleted...
main.bundle.js:97 Removing VFB_00030633 from 2
main.bundle.js:97 Passing 2 instances
/org.geppetto.frontend/geppetto/build/4.4.bundle.js:7 VFB_00030633 deleted...
main.bundle.js:97 Removing VFB_00030633 from 2

**Comment by Robbie1977** [comment]
Fixed
