### ISSUE TITLE
feature/react_refactoring: stackViewer can't be readded once closed via button

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#260]
once closed the button fails to reopen stack viewer.

FYI TermInfo button works fine.

Ref #249

**Comment by ddelpiano** [comment]
@Robbie1977 I tried this locally and on v2-dev where I saw that you deployed the new version.
Both are working fine for me, do you remember if you did something specific to trigger the issue?
Thx

**Comment by Robbie1977** [comment]
Nope seems to be fixed now
