### ISSUE TITLE
feature/react_refactoring: Selection is simply toggling rather than burrowing 

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#262]
when multiple items are stacked a single one is selected then unselected with repeated stationary clicks in the same spot.
The same actions previously would cycle down through items until looping back to the top item.

**Comment by jrmartin** [comment]
@Robbie1977 Both of those links seem to have same behavior for me, in both cases it's looping when selecting on stacked objects. Was there a specific stacked of object that can reproduce this? 

https://streamable.com/obetw
