### ISSUE TITLE
feature/react_refactoring: Need to load a default template if no id's are passed

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#263]
without the script VFB_00017894 is no longer loaded by default. This needs to be reinstated otherwise the navigation is very difficult without a starting point.

**Comment by ddelpiano** [comment]
@Robbie1977 I already took this into the scope of the other card related to the id= & i= issue, will close this together with the other.

**Comment by ddelpiano** [comment]
pushed into https://github.com/VirtualFlyBrain/geppetto-vfb/commit/9f8e46af9c60ecc2c7ddb6cd81cc5a3020794dda
