### ISSUE TITLE
Template should not be selectable on 3D canvas

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#27]
Apologies if we already have a ticket on this.  I find this behavior one of the biggest irritations when interacting with the VFB 2 canvas.  Presumably this should be straightforward as long as templates are clearly typed.  Preventing select on move would help, but I suspect will not be sufficient.  I just don't see the use case for being able to select the template with point and click on canvas.  Canvas info better displayed/accessible as separate widget.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#61
