### ISSUE TITLE
feature/react_refactoring: search not closing on action selection or clearing previous typing

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#270]
previously search always started blank (with a different message UX testing didn't like 'lightspeed search') and closed on selection of show term info.

**Comment by Robbie1977** [comment]
FYI closing the search bar should be the first thing these buttons do as this gave the user more sense of responsiveness.

**Comment by ddelpiano** [comment]
@Robbie1977 the spotlight is now cleared on closing/reopening, I am using the pre-existing method to open the spotlight and this clear already what was in buffer before.
Will look at the actions/responsiveness later on.

**Comment by ddelpiano** [comment]
action responsiveness fixed with https://github.com/VirtualFlyBrain/geppetto-vfb/commit/f0bfd45af567b66c9026123306b0b48576575360
