### ISSUE TITLE
Extreme test case for raycasting delays

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#276]
VNS has all point clouds for anatomy and causing an extreme delay on selection. So much so the unresponsive page message sometimes appears. 

Classic (dev branch):
https://v2.virtualflybrain.org/?i=VFB_00100000,VFB_00100002,VFB_00100020,VFB_00100003,VFB_00100001

React Refactored:
https://v2-dev.virtualflybrain.org/org.geppetto.frontend/geppetto?i=VFB_00100000,VFB_00100002,VFB_00100020,VFB_00100003,VFB_00100001

**Comment by tarelli** [comment]
@Robbie1977 spent some time looking into this, from what I can see it's a problem of the default raycaster we are using, as you can see from the screenshot below even after knowing it's intersecting with the bounding sphere of the object (which happens here if ( raycaster.ray.intersectsSphere( sphere ) === false ) return;)) which could be enough for us as you were saying it goes ahead and calculates all the points with which it intersects. In the example I have there's already 300,000 vertices. If there are superposed expression patterns (often the case) then that number grows a lot. 
![Screenshot 2018-10-25 at 14.21.54.png](https://images.zenhubusercontent.com/53cfecb449f8b7fd7f00149b/4b7c8cde-dff7-4fcd-b8e9-9258f92ea0ff)

This is also discussed [here](https://github.com/mrdoob/three.js/issues/5691) and [here](https://github.com/aframevr/aframe/issues/829). I can already think of some optimisations we could implement ourselves but first there's a different algorithm we could try to use - before rolling out or own entirely - called octree, with an example [here](https://threejs.org/examples/webgl_octree_raycasting.html). This is something @jrmartin could attempt, let @ddelpiano and @gidili know what priority this should have, thanks!

**Comment by jrmartin** [comment]
I attempted using the Octree library found here https://github.com/collinhover/threeoctree , it didn't help speeding up selection. The octree library is based on THREE.js revision 60 and we are on revision 87, it might be preventing it from working properly.
