### ISSUE TITLE
Look for possible library candidates to be used for the tiles layout of the new VFB2.

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#285]

**Comment by ddelpiano** [comment]
* 1. FlexLayout - react library
This has pretty much what we are looking for except few features like collapse/minimise that most likely would require some work from our side to be implemented.
* https://www.npmjs.com/package/flexlayout-react
* https://github.com/caplin/FlexLayout

* 2. Golden Layout - jquery 
Probably the most complete but not react, even though seems to be compatible but looking for this I can see few people had issues to link this library with react. 
* https://golden-layout.com/tutorials/getting-started-react.html
* https://github.com/andrewcapodieci/golden-layout-react-redux/
* https://github.com/Slowki/react-golden-layout

* 3. React Grid Layout
Looking at the API and examples seems to be nice and seems to have the potential to be extended for what we need (maximise, minimise, collapse) keeping a tile structure.
* https://github.com/STRML/react-grid-layout

* 4. React-tiles
Our first choice, still good considering the layout but what worries me the most is that according to the github page this is a beta version and the API might change a lot, also the github repo does not seems very active (1 contributor, last commit end of June). 
* https://github.com/arqex/react-tiles

Personally I would chose Flexlayout since it seems to be the most complete but probably you guys would consider one of the other a better options. @Robbie1977 @dosumis @tarelli @gidili

**Comment by Robbie1977** [comment]
@ddelpiano I can't see any float option with Flex
