### ISSUE TITLE
VFBTermInfo style fixes

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#289]
Comparing the old TermInfo with the new declarative VFBTermInfo component there are few style differences, the goal is to mirror the old style in the new component:

- Colors and font in the 'References' voice are different
old
![Screen Shot 2018-11-13 at 18.27.29.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/d1014914-21e7-4e36-a709-b516813f8d23)

new
![Screen Shot 2018-11-13 at 18.27.57 1.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/9e63720f-e91b-4fd3-851c-add7cfab19a9)

**Comment by ddelpiano** [comment]
@Robbie1977 feel free to add what you spotted in this card, so far this is the only one I can see. Thx

**Comment by Robbie1977** [comment]
Image position is the main issue on the term info.

**Comment by Robbie1977** [comment]
Colour selection is not appearing (tested in chrome)

**Comment by Robbie1977** [comment]
Interesting the moment I submitted the colour selection issue it's now appearing. It appears to be intermittent. It was failing across multiple items [template & medulla] then magically worked when I tabbed back to the page.

**Comment by ddelpiano** [comment]
closing this since it should have been fixed by jesus and it should be now in development.
Robb feel free to re-open if needed.
