### ISSUE TITLE
Stack Viewer's canvas to be centered and handle the resize of its tile

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#297]
using the branch feature/vfb_new_layout2 (same branch for frontend and geppetto-vfb repos) you can see that the stack viewer at the moment is not centered and does not resize itself at startup.
The stack viewer should place its canvas always in the center of its own tile (try to maximise, minimise and resize the tile to see different scenarios).

Also fix toggling visibility of stack and term info widgets

**Comment by ddelpiano** [comment]
@jrmartin one more note, could you try also to close and re-open the stack viewer component using the buttonbar and see if this is displayed when you reopen it? In case can you add this to the card if not displayed?
Thanks

**Comment by jrmartin** [comment]
@ddelpiano Toggling visibility for the stack viewer from the button bar don't work. Also for the term info. Added them to this card
