### ISSUE TITLE
Compound query interface cuts off long query leg names

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#30]
_From @dosumis on May 19, 2017 12:23_

![image](https://cloud.githubusercontent.com/assets/112839/26247509/1b2bc89e-3c96-11e7-9962-c2ac406ba780.png)

The second of the two images queries should end with (clustered), as in TermInfo

_Copied from original issue: VirtualFlyBrain/uk.ac.vfb.geppetto#26_

**Comment by Robbie1977** [comment]
Increased width and reduced font as a quick fix for now
