### ISSUE TITLE
TermInfo image link broken

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#300]
When clicking on the image displayed in the term info this should load the element in the scene if not yet present, at the moment this is broken and requires investigation.

**Comment by ddelpiano** [comment]
To reproduce the issue click on the stack viewer (without the shift pressed) in order to load a new element in the term info but not in the scene. (e.g. image below).

![VirtualFlyBrain (2).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/45857f65-1219-40b6-884e-344ea1027ae3)

Then click on the image inside the term info, this should load the element in the canvas but at the moment the anchor/link is broken.

![download (1).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/85871d66-6f36-497e-b09d-1241789c8f01)

My 2 cent (not sure but I would start from these) are that the issue is in the [hookup function](https://github.com/VirtualFlyBrain/geppetto-vfb/blob/918c86a639199459a17c6fad5fe6b5a8d734bc35/components/interface/VFBTermInfo.js#L232) or in the [function that constructs the html href](https://github.com/VirtualFlyBrain/geppetto-vfb/blob/918c86a639199459a17c6fad5fe6b5a8d734bc35/components/interface/VFBTermInfo.js#L137).

**Comment by jrmartin** [comment]
@ddelpiano There's a proposed fix for this on PR #316
