### ISSUE TITLE
About/Contribute/Feedback layout to be fixed

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#303]
The style of these 3 pages needs to be fixed to mirror what currently in production.

**Comment by ddelpiano** [comment]
Production: https://v2.virtualflybrain.org/
Latest: https://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto?i=VFB_00017894

Currently the pages About / Contribute / Feedback in the latest version of VFB deployed do not have the same style of what we currently have in production.
The goal is to fix these 3 pages to mirror the style currently we have in production.

To open these pages in production refer to the links in the top-right corner (above the term info) under the voices About/Feedback/Contribute as per images below:
![VFB - Virtual Fly Brain, a hub for Drosophila melanogaster neuroscience research (3).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/9cc7030a-64d4-4f1c-b9d9-973e4362c184)

To open these pages in the Latest version of VFB refer to the menu voice Virtual Fly Brain in the top-left corner (beside the mosquito icon) under the voices About/Feedback/Contribute as per images below:
![download.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/b4d534dc-54fb-4b20-970f-1c2a1aaa6d19)


Current style in Production:
![VFB - Virtual Fly Brain, a hub for Drosophila melanogaster neuroscience research (2).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/a47285ad-f940-45ff-9850-40032b29d162)

Current style in the Latest: 
![VirtualFlyBrain.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/e3f60c05-49cd-465a-9d29-f0223c062ae4)

These 3 pages are constructed starting from a string within the VFBToolbar.js component, [feedback](https://github.com/VirtualFlyBrain/geppetto-vfb/blob/c8d16bf79fccb395d1f65fa2afa425f136c15d3d/components/interface/VFBToolBar.js#L269), [About](https://github.com/VirtualFlyBrain/geppetto-vfb/blob/c8d16bf79fccb395d1f65fa2afa425f136c15d3d/components/interface/VFBToolBar.js#L349) and [Contribute](https://github.com/VirtualFlyBrain/geppetto-vfb/blob/c8d16bf79fccb395d1f65fa2afa425f136c15d3d/components/interface/VFBToolBar.js#L626).
the style should be defined in the VFBToolbar.less.
To fix this card feel free to fork the geppetto-vfb extension from the [branch release_march_2019](https://github.com/VirtualFlyBrain/geppetto-vfb/tree/release_march_2019) .

**Comment by jrmartin** [comment]
@ddelpiano This PR takes care of the remaining problems of this 

https://github.com/VirtualFlyBrain/geppetto-vfb/pull/314
