### ISSUE TITLE
Canvas selection responsiveness to improve 

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#304]
Reference issue on Three.js https://github.com/mrdoob/three.js/issues/12857

- [x] Try injecting an optimized Point.js https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/objects/Points.js that will stop testing points as soon as there is a positive. Because of the way VFB scenes are constructed this should not be a problem. The downsides of this is that for every new release of Three.js that we need to integrate we'll have to revisit the optimization if any of the internals have changed. Alternatively we could create a separate Raycaster without overwriting the default one, this is probably better but if some internals that will be used by the new Raycaster change we'll also have to update it.
- [ ] Try GPU Picker https://github.com/brianxu/GPUPicker/blob/master/GPUPicker.js

**Comment by ddelpiano** [comment]
http://localhost:8081/org.geppetto.frontend/geppetto?i=VFB_00100000,VFB_00100005,VFB_00100001

**Comment by Robbie1977** [comment]
happy with current fix minimizing bounding box calculations
