### ISSUE TITLE
Choosing a term to add to query should prompt display of query type choices

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#31]
_From @dosumis on May 19, 2017 12:28_

Choosing a term to add to query should prompt display of query type choices, instead the user just sees the canvas without any pop-up.  Choosing a query type requires going back to query icon or menu.

_Copied from original issue: VirtualFlyBrain/uk.ac.vfb.geppetto#27_

**Comment by Robbie1977** [comment]
fixed
