### ISSUE TITLE
Menus and buttonbar configuration

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#315]

**Comment by ddelpiano** [comment]
ButtonBar will be restored with search, query and layers.

**Comment by dosumis** [comment]
Some other tweaks:

1.  Menu entries need to be aligned with window header titles:
 - Canvas window -> 3D viewer
 - Choose one of stack viewer or slice viewer
 - info -> Term Info

2.  Virtual Fly Brain.Share ->  Virtual Fly Brain.social media

3. Windows -> Tools

4.  wireframe toggle should be a button on canvas, not an item in the windows/tools menu

**Comment by Robbie1977** [comment]
@ddelpiano How easy is it to get the wireframe toggle button (removed from button bar) into the 3D canvas window as this is the only outstanding action on this ticket?

**Comment by ddelpiano** [comment]
That would take me half a day roughly, I will schedule this for the next sprint agenda and will tackle it at the beginning of the week.
