### ISSUE TITLE
Query bug - queries gets stuck on old term

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#331]
When I run queries on **v2a**, I consistently fail to get the current term in the query slot - instead it is replaced by a term I've queried with or browsed to earlier.

e.g.

![image](https://user-images.githubusercontent.com/112839/57302004-22c09400-70d2-11e9-9f90-65dbd22612d8.png)

-> click part of query ->

![image](https://user-images.githubusercontent.com/112839/57302027-2e13bf80-70d2-11e9-828d-adc3d0aee38c.png)

This is not a bug Ive ever encountered before, so I assume it's been introduced relatively recently.

**Comment by dosumis** [comment]
Broken here too http://v2-dev2.virtualflybrain.org

**Comment by Robbie1977** [comment]
"partof" query not getting the correct ID from term info click handler

**Comment by ddelpiano** [comment]
Confirmed as already fixed as part of the pre-release push.
