### ISSUE TITLE
Graph Browser component requirements

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#337]
@dosumis @Robbie1977 below the main questions came out from our explorative meeting on this component and possible libraries to use:

1. Should we represents this as a 3D or 2D view? (vasturiano's library allows to switch from 2d to 3d and viceversa, see also (this)[https://github.com/vasturiano/3d-force-graph/issues/201] for future reference for myself in case this will be the chosen one).
2. Should we implement filtering per type we want to show? 
3. Which actions should we implement onClick on the node?
   3.1 Visualise the node (load 3D data, load image(s), load metadata in the terminfo) changing the focus term?
    3.2 run another query that returns more data from that node?
4. Should we go for a multiscale or a single scale navigation (using breadcrumbs to allow the user to navigate through his tree) as per image attached. ![Graph component navigation.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/8a84acb1-7717-4299-b6f0-45ddb701712d)

The implementation per node will be as much generic as possible since each node can represents different objects (neurons, images, others).

**Comment by dosumis** [comment]
We need 3 different graph widgets, all of which will  have full  underlying JSON graph specified in initial query (i.e. no dynamic querying to generate more graph during browsing)

Component 1:  Tree browser (not connected nodes) for template:  single root or small number of roots  - many branches and leaf nodes.  This one  should  be folded out to some limited number of nodes.  Would also be good if automatically folds out to focus term (this is what VFB1 does).

Component 2: Context browser - connected graph starting from one root (a bottom) - graph laid out above,

Component 3: Circuit explorer - connected graph organised in columns.  Would be good to be able to display  edge strength as thickness.

**Comment by Robbie1977** [comment]
https://github.com/vasturiano/d3-force-3d
https://github.com/vasturiano/3d-force-graph

**Comment by Robbie1977** [comment]
May be of help further down: https://www.graphviz.org/pdf/dotguide.pdf
