### ISSUE TITLE
Term info - example images only showing direct instance

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#34]
Unlike VFB 1.5, only direct instances are shown in example images for TermInfo

e.g. see 'uniglomerular antennal lobe projection neuron'

Cypher:

```cql
MATCH (c:Class)<-[:SUBCLASSOF|INSTANCEOF*]-(i:Individual) where c.short_form  = '' RETURN i
```
Basically this query: 
https://github.com/VirtualFlyBrain/VFB2/blob/alpha/html/conf/vfb.xmi#L194

Whereas, from the results, it looks like you're using this:

```cql
MATCH (c:Class)<-[:INSTANCEOF]-(i:Individual)
```

(This is broken in VFB 1.5 for painted domains, but all terms should behave the same.  So, for example, mushroom body (stage neutral) should display images of 'adult mushroom body'.)

Challenge in current struc is how to fit into the monster query currently driving TermInfo https://github.com/VirtualFlyBrain/VFB2/blob/alpha/html/conf/vfb.xmi#L263

**Comment by dosumis** [comment]
e.g. 

![image](https://user-images.githubusercontent.com/112839/27592204-d1f46a4e-5b4b-11e7-91dc-3688951d2208.png)

vs

![image](https://user-images.githubusercontent.com/112839/27592252-ebcbeb18-5b4b-11e7-8348-8b446eb01ba6.png)

But

![image](https://user-images.githubusercontent.com/112839/27592298-07bf62c8-5b4c-11e7-999d-95fc6c463609.png)

**Comment by Robbie1977** [comment]
@dosumis How many layers did you want to go down?

**Comment by dosumis** [comment]
In VFB 1.5 there is no set limit.  This is potentially slow (but could be very if we moved query to OWL).   Given that there are no semantics to 'levels' in OWL, increased detail in classifications could lead to loss of useful results as the ontology evolves.   Perhaps it would be better to set a limit to the number returned and add a link immediately under the examples allowing users to query for all?

**Comment by Robbie1977** [comment]
I've implemented 1 layer immediately and will look at limiting results based on number of results with closest given priority.

**Comment by Robbie1977** [comment]
Any Class with examples gives a query to pull all examples and this explores the full tree

**Comment by dosumis** [comment]
> I've implemented 1 layer immediately and will look at limiting results based on number of results with closest given priority.

I'm not sure proximity matters - it's just a reflection of how much we know about any given neuron/structure, rather than the nature of the neuron/structure itself.  I'd just choose an arbitrary return limit number (say 6 as elsewhere?)

> Any Class with examples gives a query to pull all examples and this explores the full tree

Excellent

**Comment by dosumis** [comment]
This should not be done as a mega query.  Needs to be done separately.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#62
