### ISSUE TITLE
Review and document queries driving site

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#36]
Queries live here: https://github.com/VirtualFlyBrain/VFB2/blob/alpha/html/conf/vfb.xmi

In a declarative schema expressed in [XMI](http://www.omg.org/spec/XMI/).

How to doc:

* Informal discussion doc with links to XMI (Github version links or XPATH?)
* script extracting queries from XML -> MD?
* Add description comment fields to XMI?

They depend on a typing system (currently) specified here: 
https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py#L43

 - [] TODO - move this out into a separate JSON file with a persistent URL

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#63
