### ISSUE TITLE
Error with compound query

### ISSUE THREAD

**Issue by filippomc** [VirtualFlyBrain/geppetto-vfb#435]
Got an error making a random compound query: ![image](https://user-images.githubusercontent.com/46561561/67023902-d313d900-f103-11e9-9ffd-a7f7cb640748.png)

This is what I see from the interface
![image](https://user-images.githubusercontent.com/46561561/67024268-6b11c280-f104-11e9-842d-da7a0b4b5114.png)

The message to the websocket is the following:

```Json
{data:` "{"projectId":-1260674925,"runnableQueries":[{"targetVariablePath":"FBbt_00007401","queryPath":"neuronsparthere"},{"targetVariablePath":"FBbt_00001267","queryPath":"Compound Ref Query Expression found here"}]}"
requestID: "Connection16-28"
type: "run_query_count"
}```

**Comment by ddelpiano** [comment]
discussing this during the sprint call, as a quick fix return 0 results in this case.
If there are multiple headers merge the headers and display all the information basing the merge on the id of the results and frontend side display everything processed/merged on backend.

**Comment by jrmartin** [comment]
Should be taken care of by PR https://github.com/openworm/org.geppetto.datasources/pull/39
