### ISSUE TITLE
Merge query results on refined query when sub-results contains different headers

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#464]
this follows what done for https://github.com/VirtualFlyBrain/geppetto-vfb/issues/435 , according to what discussed with @Robbie1977 and @dosumis .

On the datasource module, on multiple queries that the backend is processing, if the results have different headers we should.
1. Check if both the results headers contains the id column
    1a. If the id column is not present in one of them return "0 results".
2. if both the headers contains the id, intersect the id contained in both the results and merge the columns and data.

e.g.

result 1:
ID - Name - Description
01 - VFB_123 - Random neuron
02 - VFB_765 - Another neuron

result 2:
ID - Image - Type
01 - image_01 - Neuron
07 - image_07 - Neuron

The merge should produce the below:

ID - Name - Description - Image - Type
01 - VFB_123 - Random neuron - Image_01 - Neuron

**Comment by jrmartin** [comment]
Question, what happens when 2 results that share the same ID have different descriptions or Types, what's the desired merge result?

E.g.
result 1:
ID - Name -        Type    -                                                Description
01 - VFB_123  - medial lobe of adult mushroom body   -  Mushroom body
02 - VFB_765 -   Neuron                                                -  Another neuron

result 2:
ID - Image -       Type        - Description
01 - image_01 - Neuron    - Random Neuron
07 - image_07 - Neuron    - Test Description2

In the example above, should the description values  and types be combined to produce:

ID - Name -       Description                                        - Image          - Type
01 - VFB_123 - Mushroom body and Random neuron - Image_01 - Neuron and  medial lobe of adult mushroom body

**Comment by dosumis** [comment]
Not sure I understand the example, but I can see how the behaviour is badly underspecified (*Mea Cupla* - I should have been paying more attention).

Previously we only had a fixed set of columns for results tables, so could use compound keys to ensure safe  merge.  However, it should always be the case that columns with the same header name have the same content when they share an ID, so merge on ID should be safe.  Out query system is designed to ensure this.  If there are any cases where this is not true, this is a bug and should produce informative user facing and dev facing errors.  For ease of merging, we should also ensure that column order is invariant between reports.  We need a config for this.

If all of this requires further work - an MVP would just be a warning that this type of compound query is not currently supported. 

It is also possible that 2 results have the same ID but that the two results tables have different columns.  I think we should aim to avoid this, but it is unavoidable in at least one case: where we combine some query based in similarity scores (e.g. NBLAST) with semantic queries, which never have a score. In these cases I think it makes sense to keep the score column.  We could simply have the rule that the table displays the union of all columns. If this is hard to achieve, a direct specification of merged results that allows for the presence of a score column would be OK.

Again -  if this requires more work, an MVP for the new release would just be a warning to indicate that the combination  is not currently supported.

**Comment by dosumis** [comment]
Difficult case: Merging two NBLAST results.  Should we allow this?  If we do:

1. Merge on ID won't work! - score columns will differ!
1. To make results interpretable to users, we'd need a columns for query image (result X has a similarity score n when compared to (segmented) image Y) .

**Comment by dosumis** [comment]
I wrote: 
> We could simply have the rule that the table displays the union of all columns.

This seems to comply to the spec in the ref'd ticket https://github.com/VirtualFlyBrain/geppetto-vfb/issues/435#issuecomment-544922811  :

> If there are multiple headers merge the headers and display all the information basing the merge on the id of the results and frontend side display everything processed/merged on backend.

So perhaps suitable fix already in place?

**Comment by jrmartin** [comment]
Thans @dosumis for the clarification. The example I provided is one I made up thinking it could happen, not one I found while debugging. 

A real test case scenario is the one below, only difference is a new column in the second result (column : score), but the remaining column value remain the same:

First result:
[ID, Name, Definition, Type, Images]
[VFB_00002326, fru-M-200007, A(n) neuron expressing Scer\GAL4[fru.P1.D] that is part of a male Scer\GAL4[fru.P1.D] expression pattern., neuron, continuant, {"eClass":"Variable","id":"images","name":"Images","static":false,"types":[{"$ref":"geppettoModel#//@libraries.5/@types.10"}],"initialValues":[{"key":"geppettoModel#//@libraries.5/@types.10","value":{"eClass":"ArrayValue","elements":[{"eClass":"ArrayElement","index":0,"initialValue":{"eClass":"Image","data":"https://www.virtualflybrain.org/data/VFB/i/0000/2326//thumbnailT.png","name":"fru-M-200007","reference":"VFB_00002326","format":"PNG"}}]}}]}]

Second Result:
[ID, Score, Name, Definition, Type, Images]
[VFB_00002326, 0.4889, fru-M-200007, A(n) neuron expressing Scer\GAL4[fru.P1.D] that is part of a male Scer\GAL4[fru.P1.D] expression pattern. Synonym(s): FruMARCM-M000014_seg001., neuron, continuant, {"eClass":"Variable","id":"images","name":"Images","static":false,"types":[{"$ref":"geppettoModel#//@libraries.5/@types.10"}],"initialValues":[{"key":"geppettoModel#//@libraries.5/@types.10","value":{"eClass":"ArrayValue","elements":[{"eClass":"ArrayElement","index":0,"initialValue":{"eClass":"Image","data":"https://www.virtualflybrain.org/data/VFB/i/0000/2326//thumbnailT.png","name":"fru-M-200007","reference":"VFB_00002326","format":"PNG"}}]}}]}]

Merge Result will be:
[ID, Name, Definition, Type, Images, Score]
[VFB_00002326, fru-M-200007, A(n) neuron expressing Scer\GAL4[fru.P1.D] that is part of a male Scer\GAL4[fru.P1.D] expression pattern., neuron, continuant, {"eClass":"Variable","id":"images","name":"Images","static":false,"types":[{"$ref":"geppettoModel#//@libraries.5/@types.10"}],"initialValues":[{"key":"geppettoModel#//@libraries.5/@types.10","value":{"eClass":"ArrayValue","elements":[{"eClass":"ArrayElement","index":0,"initialValue":{"eClass":"Image","data":"https://www.virtualflybrain.org/data/VFB/i/0000/2326//thumbnailT.png","name":"fru-M-200007","reference":"VFB_00002326","format":"PNG"}}]}}]}, 0.4889]

**Comment by dosumis** [comment]
That's the correct behavior.

**Comment by ddelpiano** [comment]
> I wrote:
> 
> > We could simply have the rule that the table displays the union of all columns.
> 
> This seems to comply to the spec in the ref'd ticket [#435 (comment)](https://github.com/VirtualFlyBrain/geppetto-vfb/issues/435#issuecomment-544922811) :
> 
> > If there are multiple headers merge the headers and display all the information basing the merge on the id of the results and frontend side display everything processed/merged on backend.
> 
> So perhaps suitable fix already in place?

Hi David,

As you pointed out this won't work with the scores though, or at least this will break the ascending/descending order mechanism since that column will expect a single score to base the order on that.
Mistakenly I assumed the information per record was gonna be the same if the id and the header match but I understand this is not the reality

> Difficult case: Merging two NBLAST results. Should we allow this? If we do:
> 
> 1. Merge on ID won't work! - score columns will differ!
> 2. To make results interpretable to users, we'd need a columns for query image (result X has a similarity score n when compared to (segmented) image Y) .

Hi David, 

for this specific case what should we do? 
The current behaviour implies that if some of the headers match between the result sets we will take the first set of results and we add to this the columns present in the second but not in the first.
So if we have a score duplicated for the same ID we take the score from the first query.
In such scenario what should we do?
Thanks!

**Comment by dosumis** [comment]
> For this specific case what should we do?

Block. I think it's OK not to support this. See:
https://github.com/VirtualFlyBrain/geppetto-vfb/issues/466
