### ISSUE TITLE
Query for neurons in a tract is missing

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#47]
Works in VFB 1.5 .  OWL query is straightforward.  No fancy NEO queries needed.

**Comment by dosumis** [comment]
should run from 
Tract:Class

**Comment by Robbie1977** [comment]
Tract missing form production neodb

**Comment by dosumis** [comment]
Name = 'Neuron_projection_bundle'.  This is present in Neo4J prod.  Switching query to run from these should fix this ticket.

**Comment by Robbie1977** [comment]
Tested on examples
wrong xmi being run - interrelationship simplified
