### ISSUE TITLE
Querybuilder URL trigger to take into account compound queries

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#484]
this should extend the functionality already implemented for the single queries to let the user open through the URL compound queries.

**Comment by jrmartin** [comment]
For this one, the compounds queries can be separated by a semicolon, in between the id and type:
&q=FBbt_00003678,neuronspostsynaptic;FBbt_00003678,neuronspostsynaptic;FBbt_00003678,neuronspostsynaptic
@ddelpiano @Robbie1977

**Comment by ddelpiano** [comment]
aren't compound queries running on the results of the first? 
if the answer to the first is yes, why do we need to re-give the instance id in input? if the query is sufficient I would avoid to give the id multiple times.
