### ISSUE TITLE
Layer/Control Panel refactoring to fit into a pane of FlexLayout

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#486]
The control panel needs to be refactored to fit in the Flexlayout model rather than being an indipendent component living in a modal full screen.

1. For the refactoring we will switch to the [ListViewer](https://github.com/openworm/geppetto-client/tree/development/js/components/interface/listViewer) component, already used in other applications (e.g. of other implementation using the list viewer [NWBExplorer](https://github.com/MetaCell/nwb-explorer/blob/development/webapp/components/NWBListViewer.js) )

2. The component will display 4 columns, Controls, Name, Type and Thumbnail

3. The first column will have to implement a Menu when clicking on the icon, the menu will have to support the same set of controls we currently have implemented in the control panel configuration in VFB (https://github.com/VirtualFlyBrain/geppetto-vfb/blob/67a621bc106a01d55868c2fc6602ce9c083f39e1/components/configuration/VFBMain/controlPanelConfiguration.js#L48).
Note, this is currently not in the mockups, each control in the menu will have to use also the icon associated to it plus the label (this functionality it's already supported in the menu component), these can be seen in the "icon" field in the file linked above.

4. The component needs to update itself if new instances are loaded by other components (e.g. query builder).

5. We need to avoid to use string commands as done with the previous implementation of the control panel in favour of callbacks (the nwb-explorer implementation it's a good reference for that).

Mockups:

The label needs to have the same style of the others and the name should be "Layers" as currently stated in the menu for this component.

![Screenshot_2020-07-06_11-58-30.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/0650942e-d879-447a-9ee0-3afcaae5653e)

![Screenshot_2020-07-06_11-58-55.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/f98100bb-09cf-4c18-913a-26e35cedc56a)

For the color use the same component we currently use in the VFBTree, 
"import { SliderPicker } from 'react-color';"

![Screenshot_2020-07-06_11-59-15.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/1bedc5f1-e31a-41c1-b4ff-d5c40692f340)

**Comment by Robbie1977** [comment]
@ddelpiano @jrmartin how is selection shown in the list? Claire suggested having the selected row highlighted.

**Comment by ddelpiano** [comment]
@Robbie1977 we can swap the menu item between "Select" and "Unselect", depending on the selection status of the instance, the highlight it will create inconsistency with the other menu items in the list I think.

**Comment by jrmartin** [comment]
@ddelpiano  Draft PR opened here https://github.com/VirtualFlyBrain/geppetto-vfb/pull/650/files
