### ISSUE TITLE
query for tracts innervating neuropil is missing

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#49]
Query should run from synaptic_neuropil:Class

**Comment by Robbie1977** [comment]
@dosumis Is the query correct: 
http://owl.virtualflybrain.org/api/runQuery.groovy?type=subeq&query=%3Chttp://purl.obolibrary.org/obo/FBbt_00005106%3E%20that%20%3Chttp://purl.obolibrary.org/obo/RO_0002101%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003624%3E&ontology=VFB

neuron that fasciculates_with some [adult brain]

**Comment by dosumis** [comment]
> On Jul 12, 2017, at 4:36 PM, Rob Court <notifications@github.com> wrote:
> 
> @dosumis <https://github.com/dosumis> Is the query correct:
> http://owl.virtualflybrain.org/api/runQuery.groovy?type=subeq&query=%3Chttp://purl.obolibrary.org/obo/FBbt_00005106%3E%20that%20%3Chttp://purl.obolibrary.org/obo/RO_0002101%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003624%3E&ontology=VFB <http://owl.virtualflybrain.org/api/runQuery.groovy?type=subeq&query=%3Chttp://purl.obolibrary.org/obo/FBbt_00005106%3E%20that%20%3Chttp://purl.obolibrary.org/obo/RO_0002101%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003624%3E&ontology=VFB>
> 

Hmmm - not sure why this is not returning. Perhaps some minor error in query?  Could try with labels.
> neuron that fasciculates_with some [adult brain]
> 
That’s the query for neurons from a tract (also missing - we have another ticket for that). 

This one should be 

innervates some [X]      

Where X is Synaptic_neuropil

You can check the original queries in the Java driving VFB 1-1.5.

**Comment by Robbie1977** [comment]
So http://owl.virtualflybrain.org/api/runQuery.groovy?type=subeq&query=%3Chttp://purl.obolibrary.org/obo/FBbt_00005106%3E%20that%20%3Chttp://purl.obolibrary.org/obo/RO_0002134%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003748%3E&ontology=VFB 

neuron that innervates some medulla

Shouldn't this have results?

**Comment by dosumis** [comment]
Innervates is used to relate tracts/nerves to neuropils/brain regions (probably the least clear bit of the semantics).

e.g. see these results:
 
http://owl.virtualflybrain.org/api/runQuery.groovy?type=subeq&query=%3Chttp://purl.obolibrary.org/obo/RO_0002134%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00003748%3E&ontology=VFB

**Comment by dosumis** [comment]
> Hmmm - not sure why this is not returning. Perhaps some minor error in query?  Could try with labels.
>  neuron that fasciculates_with some [adult brain]
> That’s the query for neurons from a tract (also missing - we have another ticket for that).

Scratch that.  neurons fasciculate with tracts not with brains or neuropils.

This works:
http://owl.virtualflybrain.org/api/runQuery.groovy?type=subeq&query=%3Chttp://purl.obolibrary.org/obo/RO_0002101%3E%20some%20%3Chttp://purl.obolibrary.org/obo/FBbt_00007080%3E&ontology=VFB

Is used to drive: 
http://www.virtualflybrain.org/do/ont_bean_list.html?action=fasciculate&id=FBbt:00007080
