### ISSUE TITLE
Move transgene<->anatomy queries  up to under targeted_neuron/targeting split lists.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#499]
Should be part of same section

![image](https://user-images.githubusercontent.com/112839/72837732-e3010300-3c86-11ea-9859-66e653a484c0.png)
![image](https://user-images.githubusercontent.com/112839/72837768-f1e7b580-3c86-11ea-8704-47be648cb680.png)

Text -> All transgenes expressed in ...

![image](https://user-images.githubusercontent.com/112839/72837924-3f642280-3c87-11ea-9497-328223497019.png)
![image](https://user-images.githubusercontent.com/112839/72837953-4ee36b80-3c87-11ea-9015-77c90b49d776.png)

Text -> All targeted anatomy

**Comment by ddelpiano** [comment]
this looks outdated, closing but feel free to reopen if required.
