### ISSUE TITLE
Browsing sometimes => multiple TermInfo, sometimes changes existing

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#5]
I can't find any pattern to this.  Spawning lots of windows makes a mess and doesn't preserve history

**Comment by dosumis** [comment]
Background: Geppetto internal windowing is designed so that a new TermInfo window is spawned if a link is clicked with cmd depressed (mac) of ctrl depressed (windows/linux), whereas just clicking alone browses to new TermInfo within the same window.

Following discussion, it is clear that this bug happens after a new tab has been opened in the browser using cmd(t) on a mac (ctrl(t) on windows/linux).  Apparently the browser then interprets cmd/ctrl to still be depressed until it is pressed a second time.

Potential solutions: 
* A general fix for the bug with interpretation of cmd/ctrl ket status
* All browsing is within one TermInfo window.  All clicking on links, whatever else is depressed, changes what is displayed in the one TermInfo window.  I think I like this one best.  Synchronization and selection is confusing with more than one TermInfo window.

I've seen this on Chrome (56.0.2924.87) and Safari (Version 9.1.3 (11601.7.8)) .

**Comment by Robbie1977** [comment]
option removed
