### ISSUE TITLE
Geppetto isKeypressed sticking when keyup event is 'off page'.

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#531]
This issue has been flagged again and I think we need to implement either a timeout on a keypress (1 min after keydown) or a clear on page focus loss?

**Comment by jrmartin** [comment]
Found the issue here, this class is the one handling the keyboard controls and checking if a key is pressed https://github.com/openworm/geppetto-client/blob/master/js/pages/geppetto/THREEx.KeyboardState.js . It's not detecting when the Shift key is let go after being pressed, looking for a fix
