### ISSUE TITLE
Resizing stack browser window messes up slice indicator location on canvas

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#54]
Slice position indicator has wrong size  / X-Y position after resizing stack browser window

e.g. see:

![image](https://user-images.githubusercontent.com/112839/28070762-f9584542-6645-11e7-8c80-d1409fc8ec47.png)

**Comment by Robbie1977** [comment]
Size Is all wrong on Half Brain - I'm working on this the maths is off somewhere.

**Comment by dosumis** [comment]
This is a more general issue  with scaling.  Needs to be documented

**Comment by dosumis** [comment]
This should be documented as a known issue for VFB 2.0 release as we don't plan to fix it in time.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#65

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#66
