### ISSUE TITLE
Cypher query for graph component

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#542]
In order to proceed with the graph component we need the cypher query that will get the data to build it.

As per sprint call, David and Robbie will try to move part of the business logic the query in order to minimise the amount of data we will get from neo4j.

**Comment by Robbie1977** [comment]
Example queries are https://github.com/VirtualFlyBrain/geppetto-vfb/issues/170#issuecomment-509306598

**Comment by Robbie1977** [comment]
Draft Cypher queries with root added from https://app.zenhub.com/workspaces/vfb15-59c292c4286ea849ed3c9326/issues/virtualflybrain/geppetto-vfb/541.

root as short_form:

What is X: 

```cql
MATCH p=(n:Class)-[:SUBCLASSOF*..]->(x) 
WHERE (('Cell' IN  labels(x)) or ('synaptic neuropil' IN labels(x))) 
AND n.short_form = 'FBbt_00003686' return  p, n.short_form as root
```

short_form here = focus term.    Restrictions on labels probably need work to be universally applicable.

Where is X:

```cql
MATCH p=(n:Class)-[:part_of|has_synaptic_terminal_in|has_presynaptic_terminal_in|
has_postsynaptic_terminal_in|overlaps*..]->(x)
 WHERE n.short_form = 'FBbt_00003686' return  p, n.short_form as root
```

root as nodeID:

What is X: 

```cql
MATCH p=(n:Class)-[:SUBCLASSOF*..]->(x) 
WHERE (('Cell' IN  labels(x)) or ('synaptic neuropil' IN labels(x))) 
AND n.short_form = 'FBbt_00003686' return  p, ID(n) as root
```

short_form here = focus term.    Restrictions on labels probably need work to be universally applicable.

Where is X:

```cql
MATCH p=(n:Class)-[:part_of|has_synaptic_terminal_in|has_presynaptic_terminal_in|
has_postsynaptic_terminal_in|overlaps*..]->(x)
 WHERE n.short_form = 'FBbt_00003686' return  p, ID(n) as root
```


Develops_from query needs some work.  Can be left out of MVP - as long as easy to extend query list in future.

**Comment by Robbie1977** [comment]
@jrmartin @ddelpiano Here are the expanded test queries for the graph component which give some more taxing graphs. 

What is X:

```
MATCH p=(n:Entity)-[:SUBCLASSOF*..]->(x) 
WHERE (('Cell' IN  labels(x)) or ('synaptic neuropil' IN labels(x))) 
AND n.short_form = 'FBbt_00003686' return  p, n.short_form as root
```
Would need to be expanded for Individuals and hence all Anatomy:
 ```
MATCH p=(n:Entity)-[:INSTANCEOF|:SUBCLASSOF*..]->(x) 
WHERE 'Anatomy' IN  labels(x) AND 
n.short_form = 'FBbt_00003686' 
RETURN  p, n.short_form as root
```
Note: we might want to filter on FBBT terms only to avoid the double branches into CL/CARO terms but is a good test for now.


Where is X:
```
MATCH p=(n:Class)-[:part_of|has_synaptic_terminal_in|has_presynaptic_terminal_in|
has_postsynaptic_terminal_in|overlaps*..]->(x)
 WHERE n.short_form = 'FBbt_00003686' return  p, n.short_form as root
```
Would be expanded to:
```
MATCH p=(n:Entity)-[:INSTANCEOF|part_of|has_synaptic_terminal_in|has_presynaptic_terminal_in|
has_postsynaptic_terminal_in|overlaps*..]->(x)
 WHERE n.short_form = 'VFB_00001567' return  p, n.short_form as root
```
The above example is also a complex test case.
