### ISSUE TITLE
Term info links to spawn the graph component with a specific query

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#578]
![Screenshot_2020-06-02_11-20-08.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/17b93b10-ad41-4d5d-932a-1021417803a4)

As per mockup, we should be able to populate the term info with links that will spawn/refresh the graph component with a specific query (pointed by a specific label).

1. If the component is closed we need to open the graph component and be able to run the query selected.
2. If the component is open but not on focus, the component needs to re-gain focus and update the data displayed.

**Comment by ddelpiano** [comment]
@Robbie1977 @dosumis, just to be sure, do you mind to validate the functional spec above in the description? (it's pretty much what described on slack in the thread where I posted the mockups). Thx.

**Comment by dosumis** [comment]
Sorry for not posting details earlier.  I don't think there should be a universal sync  - just that some components should require manual sync from within the  component.  Here's my notes from yesterday on how sync should work within the  'term context browser' (previously referred to as the  graph):

![image](https://user-images.githubusercontent.com/112839/83511729-03f42300-a4c7-11ea-9723-36498d87ad0d.png)

**Comment by dosumis** [comment]
The sync behaviour of the current  'Tree browser' - to be renamed 'Template ROI browser', should not change.

**Comment by dosumis** [comment]
Your spec for launching from within TermInfo looks good.
