### ISSUE TITLE
Tree incomplete 

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#619]
e.g. 

![image](https://user-images.githubusercontent.com/112839/85842372-8656c680-b797-11ea-87f5-aa5bad876345.png)
![image](https://user-images.githubusercontent.com/112839/85842395-8eaf0180-b797-11ea-94be-1f29b3fabb15.png)

This happens when there is redundancy in relations in the OWL file e.g.:
![image](https://user-images.githubusercontent.com/112839/85842440-9cfd1d80-b797-11ea-86c4-ef8e46dc6e07.png)

Cases due to redundancy could be fixed with by improving redundancy stripping on the OWL file.   This will happen anyway with pipeline 2.  It's possible that it won't fix every instance of this, but I suspect instances will be rare. 

All cases are fixed by taking all paths rather than all shortest paths.  Code lives here: https://github.com/VirtualFlyBrain/geppetto-vfb/blob/development/components/configuration/VFBTree/VFBTreeConfiguration.js

-> 

```cql
MATCH (root:Class)<-[:INSTANCEOF]-(t:Individual {short_form:'VFB_00101567'})<-[:depicts]-(tc:Individual)<-
[ie:in_register_with]-(c:Individual)-[:depicts]->(image:Individual)-[r:INSTANCEOF]->(anat:Class)
WHERE has(ie.index) WITH root, anat,r,image 
MATCH p=(root)<-[:SUBCLASSOF|part_of*..]-(anat) 
RETURN collect(distinct { node_id: id(anat), short_form: anat.short_form, image: image.short_form }) 
AS image_nodes, id(root) AS root, collect(p)
```

However - there's a pretty large performance hit from this - ~ 0.7 seconds -> 7 seconds for hemibrain.   @Robbie1977 - can we live with this for now?

**Comment by dosumis** [comment]
Wondering if fails here are in part due to tests being data dependent: https://travis-ci.com/github/VirtualFlyBrain/geppetto-vfb/jobs/353873636

**Comment by Robbie1977** [comment]
@dosumis This version is now running on v2a. I'll let you decide if this has resolved the issue
