### ISSUE TITLE
Search component - 2nd specification

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#637]
As per sprint call, the aim of this card if to list what's missing in the current implementation of the search component in order to swap back to the new search.

requirements:

- display badges in the results
  - this comes from facets_annotations, it might need to filter this.
- button (or something else) to clear all the filters.
- filters must be able to switch between:
  - disabled: everything pass through.
  - checked: positive filter, so filter for that field / string / whatever.
  - crossed: negative filter, remove the results that match this filter.
- remove ID, Label and Type, leave only the sub of Type as filters (adult, larval, etc).

The filter needs to switch to an AND (e.g. select adult and image must give only records that fit adult AND image, not just merge whatever fit one single filter). (this must be configurable in the json).

- additional information displayed per record after a timeout (similar to the tooltip in the template ROI).

**Comment by Robbie1977** [comment]
Resolves https://github.com/VirtualFlyBrain/geppetto-vfb/issues/205

**Comment by Robbie1977** [comment]
Labels will work as filters:
Nothing selected then everything returned
Terms selected filtered with an AND so Adult + Images will only return Adult Images Not Adult OR images.
Ideally we need filters to toggle ```[] [tick] [cross]``` with a 3rd negative filter to exclude all matching.
