### ISSUE TITLE
Finalise and implement queries for classification & location in context browser.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#648]
Current queries here:

https://github.com/VirtualFlyBrain/geppetto-vfb/issues/542

Basic queries are in place on this ticket, but still need to discuss how upper end is anchored - by type?  By template?

**Comment by dosumis** [comment]
What is X:
```cql
MATCH p=(n:Entity)-[:INSTANCEOF|:SUBCLASSOF*..]->(x) 
WHERE 'Anatomy' IN  labels(x) AND 
n.short_form = 'FBbt_00003686' 
RETURN  p, n.short_form as root
```

Where is X:
```cql
MATCH p=(Entity)-[:INSTANCEOF:part_of|has_synaptic_terminal_in|has_presynaptic_terminal_in|
has_postsynaptic_terminal_in|overlaps*..]->(x)
 WHERE n.short_form = 'FBbt_00003686' return  p, n.short_form as root
```

TBD: How to set the upper limits of terms to display in graph.  We need to stop these spiralling off into abstract land.  

Options:
  - 1.  Restrict X to upper level derived neo labels  (gross typing).  Problem: these are not currently comprehensive.  We'll have some cases where no graph is displayed.  However, this is probably good enough for cells and the nervous system.
  - 2.  Restrict X to a set of preferred roots.  This will result in less fragmented graphs being returned.   Potential problem:  Is the ontology complete enough?

**Comment by dosumis** [comment]
List of labels to use for restriction for now:
    Cell, Synaptic_neuropil, Ganglion, Neuron_projection_bundle

Test - and expand list as needed later (probably need Sensory_organ, Tagma, segment, Neuromere)

**Comment by dosumis** [comment]
Any progress?  Is above description sufficient?

**Comment by Robbie1977** [comment]
https://github.com/VirtualFlyBrain/geppetto-vfb/blob/pipeline2/components/configuration/VFBGraph/graphConfiguration.js
