### ISSUE TITLE
query is crashing the UI

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#652]
1. load http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto
2. open spotlight
3. search for FBbt_00002303
4. from term info click 'Reports of transgene expression in A1-7 DO1 motor neuron'
5. click on the only result in the query builder
6. click on 'Anatomy P{GAL4-per.BS} expression pattern is expressed in'

stacktrace:

```
  | Slick.initADA | @ | slick.js:1306
-- | -- | -- | --
  | Slick.init | @ | slick.js:1287
  | Slick | @ | slick.js:182
  | $.fn.slick | @ | slick.js:3002
  | componentDidMount | @ | slideshowImageComponent.js:165
  | commitLifeCycles | @ | react-dom.development.js:19814
  | commitLayoutEffects | @ | react-dom.development.js:22803
  | callCallback | @ | react-dom.development.js:188
  | invokeGuardedCallbackDev | @ | react-dom.development.js:237
  | invokeGuardedCallback | @ | react-dom.development.js:292
  | commitRootImpl | @ | react-dom.development.js:22541
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | commitRoot | @ | react-dom.development.js:22381
  | finishSyncRender | @ | react-dom.development.js:21807
  | performSyncWorkOnRoot | @ | react-dom.development.js:21793
  | (anonymous) | @ | react-dom.development.js:11089
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js:11084
  | flushSyncCallbackQueue | @ | react-dom.development.js:11072
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21199
  | enqueueSetState | @ | react-dom.development.js:12639
  | Component.setState | @ | react.development.js:471
  | switchView | @ | queryBuilder.js:328
  | queryDoneCallback | @ | queryBuilder.js:939
  | (anonymous) | @ | QueriesController.js:37
  | parseAndNotify | @ | MessageSocket.js:310
  | processBinaryMessage | @ | MessageSocket.js:327
  | GEPPETTO.MessageSocket.socket.onmessage | @ | MessageSocket.js:106

```
  | overrideMethod | @ | react_devtools_backend.js:2273
-- | -- | -- | --
  | console.error | @ | VFBMainContainer.js_+_105_modules:73942
  | logCapturedError | @ | react-dom.development.js:19527
  | logError | @ | react-dom.development.js:19564
  | callback | @ | react-dom.development.js:20744
  | callCallback | @ | react-dom.development.js:12490
  | commitUpdateQueue | @ | react-dom.development.js:12511
  | commitLifeCycles | @ | react-dom.development.js:19858
  | commitLayoutEffects | @ | react-dom.development.js:22803
  | callCallback | @ | react-dom.development.js:188
  | invokeGuardedCallbackDev | @ | react-dom.development.js:237
  | invokeGuardedCallback | @ | react-dom.development.js:292
  | commitRootImpl | @ | react-dom.development.js:22541
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | commitRoot | @ | react-dom.development.js:22381
  | finishSyncRender | @ | react-dom.development.js:21807
  | performSyncWorkOnRoot | @ | react-dom.development.js:21793
  | (anonymous) | @ | react-dom.development.js:11089
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js:11084
  | flushSyncCallbackQueue | @ | react-dom.development.js:11072
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21199
  | enqueueSetState | @ | react-dom.development.js:12639
  | Component.setState | @ | react.development.js:471
  | switchView | @ | queryBuilder.js:328
  | queryDoneCallback | @ | queryBuilder.js:939
  | (anonymous) | @ | QueriesController.js:37
  | parseAndNotify | @ | MessageSocket.js:310
  | Show 2 more frames
```

**Comment by jrmartin** [comment]
@ddelpiano This stack trace is fixed with this open PR from geppetto-client https://github.com/openworm/geppetto-client/pull/339

With the fix above , the query builder comes up, but the results for  'Anatomy P{GAL4-per.BS} expression pattern is expressed in' have duplicates and queries that come back without images. 

![Screenshot from 2020-09-22 16-23-27.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/3612ab29-5377-4ef8-af52-efe93557db12)![Screenshot from 2020-09-22 16-23-41.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/48514adb-9c9a-405a-ab84-1908d7744e37)
