### ISSUE TITLE
Circuit browser - edge weights and more requirements

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#657]
1. Add input text in the circuit browser configuration to express the weight to be passed to the query, do not beautify this for now, style will come during the sprint.

2. Update the component to use the below query - component wise I can see this is already done, I am adding this here to verify with Robb and David, but this can be tweaked later anyway, being aware that we need to pass hops and weight.

```
var locationCypherQuery = ( instances, hops, weight ) => ({
  "statements": [
    {
      "statement" : "WITH [" + instances + "] AS neurons"
      + " WITH neurons[0] as root, neurons[1..] AS neurons"
      + " MATCH p=(x:Neuron {short_form: root})-[:synapsed_to*.." + hops.toString() + "]->(y:Neuron)"
      + " WHERE y.short_form IN neurons AND"
      + " ALL(rel in relationships(p) WHERE exists(rel.weight) AND rel.weight[0] > " + weight.toString() + ")"
      + " WITH root, relationships(p) as fu, p AS pp"
      + " UNWIND fu as r"
      + " WITH root, startNode(r) AS a, endNode(r) AS b, pp"
      + " MATCH p=(a)<-[:synapsed_to]-(b)"
      + " RETURN pp, p, root",
      "resultDataContents": ["graph"]
    }
  ]
});
```

3. The results should be uni-directional, as per image below, and this should be already computed from the results we obtain from the query, so there should be nothing to do for us here.
Classes won't have wights available, in this case we keep showing the label variable we use right now, so if weight is available this takes priority differently we do the same as now.

![108082978-83804d00-706a-11eb-842b-d27fd557e1e7.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/10330527-295d-406b-8bdd-9adc821b4fa3)

4. Labels used for the edges should now be replaced by the weight provided by the new data, this value can be found in the relationship property provided in the data results, as per screenshot below. We might need to update the function we have in the web worker to process the results to provide the new data to the react component since from a first analysis I do not see the weight in the data we have in the VFBCircuitBrowser.

![Screenshot 2021-03-01 at 12.36.13.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/545d82ab-af06-47ac-b298-db812f62d7d5)

5. Line thickness should be expressed as natural log of the weight provided, rounding the value to the closest integer. Thickness cannot be less than 1.

6. First and last instances needs to be pinned respectively on the left (the first) and on the right (the last), keeping the columns layout we currently have.

7. With the new query we should 2 graph, one represents the primary route we need to display, the other represents the reverse path where available. We need to display edges with a single direction, coming from the primary route graph, then we need to consume the second graph and add to each weight the reverse weight and display this inside [ X ].
Note, start node and end node will be reversed in the second graph, we need to take this into account traversing the reverse graph.
So, we need to display something like:

---- 6 [4] ---> (just an example) if primary route weight is 6 and the reverse is 4.
If the reverse weight is not available we put 0 instead of missing value, like here
---- 6 [0] --->

8. (For Dario) Discuss with Jesus and Paul the following:
- The component needs to display more than one label/color for each node. 
  - Just discussed this, the node square is an html canvas so we can draw basically whatever we want, based on the design we can do estimates on the time required.
- The component might want to display additional info for each node.

9. add UI test where the 3 neurons used for the implementation are given to the component in input, generate an image and confront this with a previous reference done to let the test pass.

**Comment by dosumis** [comment]
These edges have weights:

subject | object
-- | --
"VFB_jrchjrch" | "VFB_jrchk43f"
"VFB_jrchjrch" | "VFB_jrchjrr0"
"VFB_jrchjrch" | "VFB_jrchjsg5"

Working out how to scale the edge thickness may be an issue.  The data currently has a range of 1 to 247. Will full data load, some will be in the thousands.

**Comment by dosumis** [comment]
Now we have real data, it is clear that edge weights vary enormously.  If we are to display this using line thickness we may need to use a log scale for scaling thickness.

Edge attributes to use:  weight

Example:

```cql
MATCH p=(i:Neuron { short_form: 'VFB_jrchjrch'})-[:synapsed_to]-(j:Individual) return p limit 2
```

=>
```json
{
  "iri": "http://virtualflybrain.org/reports/VFB_jrchjrch",
  "curie": "VFB:jrchjrch",
  "short_form": "VFB_jrchjrch",
  "label_rdfs": [
    "5-HTPLP01_R - 1324365879"
  ],
  "sl": "54HTPLP01_R_4_1324365879",
  "comment": [
    "tracing status-Roughly traced, cropped-False"
  ],
  "qsl": "54HTPLP01_R_4_1324365879",
  "label": "5-HTPLP01_R - 1324365879"
}
,
{
  "iri": "http://purl.obolibrary.org/obo/RO_0002120",
  "weight": [
    9
  ],
  "label": "synapsed to",
  "type": "Related",
  "short_form": "RO_0002120"
}
,
{
  "iri": "http://virtualflybrain.org/reports/VFB_jrchjs6s",
  "curie": "VFB:jrchjs6s",
  "short_form": "VFB_jrchjs6s",
  "label_rdfs": [
    "AVLP372_R - 1480532936"
  ],
  "sl": "AVLP372_R_4_1480532936",
  "comment": [
    "tracing status-Roughly traced, cropped-False"
  ],
  "qsl": "AVLP372_R_4_1480532936",
  "label": "AVLP372_R - 1480532936"
}
```

Question:  How to deal with having weights in both directions - see.

![image.png](https://images.zenhubusercontent.com/595232dc61b4ca3b0a726d41/675c5da1-db20-40e0-b52a-3f201be50746)

Answer: Follow synapse_to in one direction - but second round of queries finds all reverse direction for all pairs found by first.

**Comment by ddelpiano** [comment]
@dosumis tagging you as requested at the sprint call

**Comment by Robbie1977** [comment]
Continuing from #560

**Comment by dosumis** [comment]
TODO: @Robbie1977 & @dosumis to update query spec ASAP.

**Comment by Robbie1977** [comment]
Existing component cypher query currently in use: ```WITH [" + instances + "] AS neurons
MATCH p=(x:Class)-[:synapsed_to*.." + hops.toString() + "]->(y:Class)"
WHERE x.short_form in neurons and y.short_form in neurons
RETURN p, neurons
resultDataContents": ["graph"]

**Comment by dosumis** [comment]
New query: 

```cql
WITH ['VFB_jrchjsfu', 'VFB_jrchjs1t'] as neurons, 'VFB_jrchjrch' as root 
MATCH p=(x:Neuron {short_form: root})-[r:synapsed_to*..3]->(y:Neuron) 
WHERE  y.short_form in neurons and all(rel in relationships(p) 
WHERE exists(rel.weight) and rel.weight[0] > 70) RETURN p
```

Where root = first term in list, neurons = all others.  *..3 takes hops.

@Robbie1977  to add var names

**Comment by jefferis** [comment]
@dosumis a note that it might be good to explore a couple of other compressive options for edge weight e.g. sqrt transform rather than log transform.

**Comment by dosumis** [comment]
Natural log looked like a good fit from a quick look at the range: https://github.com/VirtualFlyBrain/geppetto-vfb/issues/658#issuecomment-769753194  - but very happy to try other.
