### ISSUE TITLE
Circuit browser - edges weight implementation

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#658]
Edges can have weights. These should be displayed as both annotations on the edge and as line-thickness. 
Implementation needs to follow whatever data/information we need to process in the graph component, more info in the linked card.

**Comment by ddelpiano** [comment]
@jrmartin I am assigning this to @dosumis since (as per sprint call) we need some fake data that David will provide us to work on the implementation.

Thx

**Comment by ddelpiano** [comment]
@dosumis @Robbie1977 could you please clarify these points below? Thanks!

- Cutoff behaviour: should the cutoff sum the weight from the root node of the graph and cut all the nodes once the weights sum for each node is above the value defined by the user? 

- If I understood correctly we have directional weights, should we consider a single direction for the cutoff (from root moving above) ?

- “config should also allow for a minimum number in this box in case data is clipped” what this means exactly for what it concern the component behaviour?

- Edge weight, what does the log scale mean in terms of implementation?

**Comment by dosumis** [comment]
> Cutoff behaviour: should the cutoff sum the weight from the root node of the graph and cut all the nodes once the weights sum for each node is above the value defined by the user?

No - this is per edge.

> If I understood correctly we have directional weights, should we consider a single direction for the cutoff (from root moving above) ?

Yes.  This will be the same direction as we use for querying.

> “config should also allow for a minimum number in this box in case data is clipped” what this means exactly for what it concern the component behaviour?

Users cannot enter a value lower than the minimum (set by config).  It they try to, they get a warning that this value is not allowed because connections with weights below this minumum are not in the database.   Maybe not MVP.  @Robbie1977 ?

>Edge weight, what does the log scale mean in terms of implementation?

If we assume a range of edge weights from 1 - n*10^3 (highest one we currently have = 4299) and we are using edge width to indicate edge weight, we obviously can't use linear scaling.  I think a natural log of weight could give us a usable spread.  Rounding would depend on what graph rendering can take as input.  If only whole numbers then just round to the nearest with min 1.

**Comment by ddelpiano** [comment]
From the sprint call with Robb and David:

1. We will just pass the cutoff value to the query, the query will do the rest and then we consume the response data.
2. Same, this will do by the query.
3. nothing to add.

**Comment by dosumis** [comment]
Query with weights is here:  https://github.com/VirtualFlyBrain/geppetto-vfb/issues/657#issuecomment-779327639

@Robbie1977 working on version with vars + reverse direction weights.

**Comment by Robbie1977** [comment]
Full query with reverse edges:
```
WITH ['VFB_jrchjrch','VFB_jrchjsfu', 'VFB_jrchjs1t'] as neurons with neurons[0] as root, neurons[1..] as neurons MATCH p=(x:Neuron {short_form: root})-[r:synapsed_to*..3]->(y:Neuron) WHERE  y.short_form in neurons and all(rel in relationships(p) WHERE exists(rel.weight) and rel.weight[0] > 70) with root, relationships(p) as fu UNWIND fu as r with root, startNode(r) as a, endNode(r) as b MATCH p=(a)-[:synapsed_to]-(b) RETURN p, root```

**Comment by Robbie1977** [comment]
JS formatted query:
```
"statements": [
    {
      "statement" : "WITH [" + instances + "] AS neurons"
      + " WITH neurons[0] as root, neurons[1..] AS neurons"
      + " MATCH p=(x:Neuron {short_form: root})-[:synapsed_to*.." + hops.toString() + "]->(y:Neuron)"
      + " WHERE y.short_form IN neurons AND"
      + " ALL(rel in relationships(p) WHERE exists(rel.weight) AND rel.weight[0] > 70)"
      + " WITH root, relationships(p) as fu"
      + " UNWIND fu as r"
      + " WITH root, startNode(r) AS a, endNode(r) AS b"
      + " MATCH p=(a)-[:synapsed_to]-(b)"
      + " RETURN p, root",
      "resultDataContents": ["graph"]
    }
  ]```

**Comment by Robbie1977** [comment]
When weight is available on edge then just show that value as the edge label:
![Screenshot 2021-02-16 at 15 19 08](https://user-images.githubusercontent.com/4630768/108082978-83804d00-706a-11eb-842b-d27fd557e1e7.png)

**Comment by ddelpiano** [comment]
@jrmartin great job with the component, few minor below.

1. the label Weight seems disaligned, also the color of the text should be in line with the others (white).

![Screenshot 2021-03-30 at 11.49.24.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/00b5d93a-9c81-419b-825d-d3e71ce95778)

2. Probably usability wise would make more sense to trigger the refresh also when I click enter in one of the input text to either update the weight or to add a instance id, @Robbie1977 @dosumis what do you think? 

Thanks

**Comment by Robbie1977** [comment]
For the automatic refresh maybe just highlighting the refresh button in some way might be better just in case the user needs to make multiple changes. As the refresh may not be quick.
