### ISSUE TITLE
Circuit browser - Link in term info for neuron instances

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#659]
If the instance on focus is a neuron, we need to display an additional link in the term info (same style of the links used to open the query builder or the link recently added to open the graph component executing different cypher queries).
When the link is clicked the instance is added to the list of neurons in the circuit browser (e.g. if we have already 2 ids in the circuit browser and we click on the link of one instance not currently in the scope of the circuit browser, this will add this 3rd neuron and will re-execute the cypher query to generate the new graph).
Note:
- if the id/instance is already part of the circuit browser neurons' list we just open/move the focus on the circuit browser but we don't add the id.
- if the component is closed and I click on the link I open the component and add this id.
- Question for @Robbie1977 , if we have already reached the max number of neurons for the circuit browser and we click the link to add another instance, should warn the user that this is not possible? 

Last note, please add a couple of scenarios to the automated tests for this feature.

Thx

**Comment by jrmartin** [comment]
This is done in branch feature/659 , only thing missing is how to figure out when an instance is a neuron.  Is there a way to verify an instance is a neuron? I couldn't find a property in the object that identifies it as a neuron.
