### ISSUE TITLE
Circuit browser - implement legend for the colors displayed

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#662]
The circuit browser needs a legend that display the different type linked to each color used for the nodes.
Starting from the color list provided, show a legend in the top-right corner (as per mockup attached) that list only the color currently rendered with the corrispetive type associated to the color (the type can be extracted from the list itself since each color is associated to a key (the type) and that string is what we should display.

![Screenshot 2020-08-27 at 23.43.31.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/b0bce2a7-f1dc-4fc6-834d-138ee0b237be)

**Comment by jrmartin** [comment]
Done in https://github.com/VirtualFlyBrain/geppetto-vfb/pull/675 @ddelpiano
