### ISSUE TITLE
Circuit browser bug with the neuron's link in the term info

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#679]
I spotted mainly 2 issues but I guess the root is the same:

1. the link in the term info sometimes does not instantiate the second neuron (and all the next if the second is set manually) in the configuration panel.

2. I tried the link with 2 neurons already configured in the circuit browser, I would expect the link to add an input text (same action that we should use manually to add a third neuron) and put the neuron in the input text but that does not happen.

Thanks!

**Comment by jrmartin** [comment]
@ddelpiano This is one fixed , PR at https://github.com/VirtualFlyBrain/geppetto-vfb/pull/688
