### ISSUE TITLE
Layers - highlight instance selected

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#708]
We need to highlight the instance on focus/selected if this is displayed in the layer component, as per example below

![Screenshot 2020-10-21 at 00.50.44.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/b3d75d43-28ec-4e7d-8496-71960aa8103b)

**Comment by dosumis** [comment]
Perfect.  Thanks.

**Comment by Robbie1977** [comment]
@ddelpiano yep that will have to do had a play and everything else looks terrible or doesn't work with griddle.
