### ISSUE TITLE
Selection of Template in 3D viewer

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#728]
Can we skip selecting the template and move to the next object down in the selected path as this sort of template selection is no longer needed.

**Comment by ddelpiano** [comment]
@Robbie1977 what about the stack viewer? 
this would not work on the canvas component itself but will re-use the logic already in place since we are storing in window.templateID the id that we should avoid the selection for and then wrap this logic around that instance id.

**Comment by jrmartin** [comment]
Hello @Robbie1977 , couple questions about this:

If the selection of the template is prevented in the 3D Viewer, the user will lose the ability to click the template in 3D Viewer and have the Term Info display the template's metadata. Is it okay to lose this feature? The user will have to have another way of selecting the template to view its metadata.

Also, if we prevent the selection of the template in the 3D Viewer, do we do the same in the Layers component and disable the selection/deselection controls for the template?

**Comment by Robbie1977** [comment]
Happy to lose selection of the template as there are now plenty of ways to get to it and it's not usually something users want.

The slice viewer already prevents template selection. 

The selection itself isn't the problem it's just that it gets in the way of selecting an item in 3D as it always the first thing hit which confuses users. In short the selection in Term Info. and the Layer tool can stay.
