### ISSUE TITLE
Stack Viewer colour update

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#80]
on item loading sometimes there is no update after the new colour is applied.

Check the event handling and ensure update triggers after the change has passed through fully.

**Comment by dosumis** [comment]
Could be down balancer playing up.  Robbie to investigate further and document.

**Comment by Robbie1977** [comment]
After latest unrelated fixes no longer present - Keeping an eye out for it again.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#95
