### ISSUE TITLE
Resolve pipeline loading of production from KB

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#82]
Check code and setup easy loading of production from KB and FB

**Comment by dosumis** [comment]
COde in place.  Perhaps needs better doc?

**Comment by dosumis** [comment]
KB -> OWL is now be working (using modified Jython code).  Is this sufficient to close the ticket?

From your text: "Check code and setup easy loading of production from KB and FB"  it looks like it encompasses FB->Prod code.  But that seems a bit too broad and is likely redundant with other tickets.  OK to move to QA?

**Comment by dosumis** [comment]
Ignoring FB, there are 4 jobs that need to run for KB -> Prod to be complete.  Each of these should correspond to a Jenkins job

1. KB -> OWL (Now working with hacked Jython code) [Jenkins job](https://blanik.inf.ed.ac.uk:8079/job/Build_VFB_ind_from_KB/)
2. OWL -> Prod:
    * OLS code  Jenkins job = ???
    * Side loading (Jython code - should still be working.  Need to check)  Jenkins job = ???
4. KB -> Prod - direct loading via Python  (Did this ever become a Jenkins Job?)

**Comment by dosumis** [comment]
Jenkins job -> pipeline mapping needs general doc.  This should probably be hyperlinks . from the pipeline doc:  

https://github.com/VirtualFlyBrain/VFB/blob/master/doc/pipeline.md

**Comment by dosumis** [comment]
Tests running here: https://travis-ci.org/VirtualFlyBrain/pipeline

**Comment by Robbie1977** [comment]
Pipeline running here: https://blanik.inf.ed.ac.uk:8079/view/Rancher/job/Load%20Production%20DB%20from%20Current%20OWL/

Result of first load here:
http://pdb-firstload.virtualflybrain.org/browser/
