### ISSUE TITLE
Long term names => loss of query details 

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#83]
For example, ("clustered") is clipped from the end of Query for:

neurons with some part in the antennal mechanosensory and motor center (clustered)

Suggested Fix: Pop up the full text when mousing over the query.

**Comment by dosumis** [comment]
![image](https://user-images.githubusercontent.com/112839/31961973-34f71c3a-b8f4-11e7-9b38-f02dbd0a506b.png)

![image](https://user-images.githubusercontent.com/112839/31962024-4d403b28-b8f4-11e7-8bcd-63a5c6510312.png)

**Comment by dosumis** [comment]
Poss solution - float over => full text.

**Comment by dosumis** [comment]
Or clip the name with ... ?

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#97
