### ISSUE TITLE
Duplicate relationships on neurons in v2a

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#85]
VFB1.5:
![image](https://user-images.githubusercontent.com/112839/32450144-63e43b56-c30b-11e7-8000-9bf095a09bb1.png)
![image](https://user-images.githubusercontent.com/112839/32450104-4645211e-c30b-11e7-869e-f7d290d61af8.png)

V2a: 
![image](https://user-images.githubusercontent.com/112839/32450181-7da3764c-c30b-11e7-9218-5b80e37d384a.png)
![image](https://user-images.githubusercontent.com/112839/32450199-8c2e4cfa-c30b-11e7-9363-6d4f70889afe.png)

**Comment by Robbie1977** [comment]
fixed for example
