### ISSUE TITLE
Split Relationships into Sections

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#90]
Anatomical, expression, etc.

It's hard for users to separate out and spot different types of information in the relationships section:

e.g.:

![image](https://user-images.githubusercontent.com/112839/32547552-b14bb1a6-c47a-11e7-99d3-4d78c758135e.png)

This could be improved if we split out relationships into different types:  Anatomy-> anatomy; anatomy -> gene and then sort alphanumerically within that list.

Relationship type could potentially be pre-computed in Neo4J.

**Comment by temjones** [comment]
Example:
<img width="315" alt="screen shot 2017-11-08 at 11 46 48" src="https://user-images.githubusercontent.com/22234198/32547575-c896eb6e-c47a-11e7-93e9-f97c4f97faa6.png">

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#101
