### ISSUE TITLE
Selecting term for query should display available queries rather than moving onto next search box

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#92]
when the term is selected open the available queries rather than moving onto next search box

**Comment by dosumis** [comment]
Currently: 

![image](https://user-images.githubusercontent.com/112839/32548826-f8b9351e-c47e-11e7-8583-4b83eb6a4ef9.png)

Should open list by default:

![image](https://user-images.githubusercontent.com/112839/32548849-13f69d12-c47f-11e7-96f2-c0bff5ed7ec3.png)

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#102
