### ISSUE TITLE
Users need help to understand icons

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#93]
UX testing shows that users are confused about what functionality is available via the various icons.

![image](https://user-images.githubusercontent.com/112839/32548035-22c59166-c47c-11e7-81b4-292b9bd17742.png)

Tool tips are slow.  Consider adding a guide to these icons that appears when users first start.  

See example from wormbase http://www.wormbase.org/#012-34-5

![](http://www.wormbase.org/img/tutorial.png)

(This could replace the splash screen)

**Comment by Robbie1977** [comment]
![](http://www.wormbase.org/img/tutorial.png)

**Comment by Robbie1977** [comment]
Add text for detailed help on slice viewer.

**Comment by dosumis** [comment]
- [ ] TODO: Make mockup of how this will look.  This will guide dev and could be used in UX testing prior to implementation.

**Comment by aoifelarkin** [comment]
Had a go at this, but think it would be best to get feedback from UX testing first to see which icons or tasks users have particular trouble with (and general feedback on the homepage). This should provide guidance as to what might particularly need targeting for extra info.
![vfb extra home page guidance](https://user-images.githubusercontent.com/22240137/33662119-98e95938-da82-11e7-8b45-7dfa37e93f66.png)

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#103
