### ISSUE TITLE
Simplify behavior after search

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/geppetto-vfb#94]
Current behavior is non-standard.  Instead of just selecting a result and pressing return, a user has to choose between icons 

e.g.
![image](https://user-images.githubusercontent.com/112839/32547680-317c09ca-c47b-11e7-8f5b-f26ef2609a55.png)

![image](https://user-images.githubusercontent.com/112839/32547708-4a63be9c-c47b-11e7-9a02-1d51d5c76956.png)

Based on current UX testing, this causes users to pause.  We should consider simplifying.

**Comment by Robbie1977** [comment]
This issue was moved to VirtualFlyBrain/VFB2#104
