### ISSUE TITLE
Check font is readable in all Browsers as currently inconsistent results.

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#97]
Safari is currently worse than firefox and chrome is best.

**Comment by ah963** [comment]
<img width="716" alt="screen shot 2017-11-08 at 12 31 36" src="https://user-images.githubusercontent.com/26765505/32549373-1bbf8ac0-c481-11e7-8690-7c5c7b7e964f.png">
Font is harder to read using Safari - poor contrast & thinner
Safari on left, Firefox on right.

**Comment by Robbie1977** [comment]
With Chrome:

![image](https://user-images.githubusercontent.com/4630768/32549462-71a90902-c481-11e7-999b-ffcbaa2ee512.png)

**Comment by Robbie1977** [comment]
Have converted from (twitters standard):
```font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;```
to (Googles standard):
```
font-family: arial, sans-serif;
```

Easier to read and more consistent across 3 browsers on local tests.

Please recheck on your own systems?

**Comment by ah963** [comment]
<img width="698" alt="screen shot 2017-11-09 at 08 28 18" src="https://user-images.githubusercontent.com/26765505/32595609-71935010-c528-11e7-83e0-2e99d9fa4da0.png">

Much clearer on Safari (left), but still slight differences with on Firefox (right).

Text under buttons now displaying properly in all browswer (Safari below)

<img width="1014" alt="screen shot 2017-11-09 at 08 33 26" src="https://user-images.githubusercontent.com/26765505/32595702-c3f03954-c528-11e7-95d4-c2ef1db0adeb.png">

**Comment by aoifelarkin** [comment]
Attaching screenshots of chrome, firefox and safari views - think Safari looks better than before. Still some differences across browsers, but reckon the improvement makes the differences acceptable now.
![chrome](https://user-images.githubusercontent.com/22240137/32611672-2979e4f2-c55e-11e7-9497-5b308f44e504.png)
![firefox](https://user-images.githubusercontent.com/22240137/32611681-2d5e0b7a-c55e-11e7-9dd1-679441e7ad88.png)
![safari](https://user-images.githubusercontent.com/22240137/32611685-2f53a836-c55e-11e7-9a27-5f029a6b77c0.png)

**Comment by dosumis** [comment]
Closing as everyone seems happy.  Please re-open if this is still an issue.
