### ISSUE TITLE
Connectivity browser - SOLR to be plugged to the current filter/input text

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#985]
we need to connect the input text to the SOLR server, same as we currently do in geppetto for the search component.
it will be less time consuming extract the logic required from the search and fit this in the connectivity browser widget used for the configuration since modifying the search will take much more time.

Please keep the solr configuration in a json format as we currently do for the other components.

**Comment by ddelpiano** [comment]
@Robbie1977 could you please provide us the query you want us to use with the component?

We will work on the implementation using the same one we have for the search for now, thx.

**Comment by Robbie1977** [comment]
The filter is simply another ```fq:"facets_annotation:Neuron"``` added in the same query as used for search
